force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Represents a call to the logging framework. 
For each trigger instance, a &quot;Log Transaction&quot; record will be created. 
For each event instance, a &quot;Log&quot; record will be created.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>The name of the apex class which generated the log. Since Exception.getStackTraceString() does not work in managed packages, this can be used to give at least some context of where the log was generated.</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Details the current execution context when the log was generated.
Displays a System.Quiddity value:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</description>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message. Values are derived from Apex&apos;s standard LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Logged_At__c.field-meta.xml
<CustomField>
    <fullName>Logged_At__c</fullName>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>The Salesforce ID of the User which generated the log. This is always UserInfo.getUserId(). Maps to the &quot;Owner&quot; field on the &quot;Log Transaction&quot; object.</description>
    <label>Running User</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Indicates the order in which logs in the same transaction were inserted (beginning with 1).</description>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>In apex, displays the detailed origin of the log request. Maps to the field of the same name on the &quot;Log&quot; object.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>The Id of the execution window in which the event was published</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/Log_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Log Setting</label>
</CustomObject>

force-app/main/default/objects/Log_Setting__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When unchecked, no logs will be published regardless of the Level</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&quot;NONE&quot;</defaultValue>
    <description>Possible values correspond with the standard LoggingLevel Enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm
Unfortunately, picklists are not available for Custom Settings</description>
    <inlineHelpText>Possible values:
NONE: No logging.
ERROR: Error and exception logging.
WARN: Warning logging.
INFO: Informational logging.
DEBUG: User-specified debug logging.
FINE: High level of logging.
FINER: Higher level of logging than FINE.
FINEST: Highest level of logging.</inlineHelpText>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger_Test.cls
@IsTest
private class Logger_Test {
	@IsTest
	static void shouldSetCorrectValues() {
		Logger.Settings = getActiveSettings(LoggingLevel.DEBUG);

		Logger.debug(Logger_Test.class, 'This is a test!');

		System.assertEquals(1, Logger.PendingLogs?.size(), 'Wrong # of Pending Logs');
		Log_Event__e logEvent = Logger.PendingLogs[0];
		System.assertEquals(String.valueOf(Logger_Test.class), logEvent?.Apex_Class__c, 'Wrong Apex Class');
		System.assertEquals(System.Request.getCurrent().getQuiddity().name(), logEvent?.Context__c, 'Wrong Context');
		System.assertEquals(LoggingLevel.DEBUG.name(), logEvent?.Level__c, 'Wrong Level');
		System.assertNotEquals(null, logEvent?.Logged_At__c, 'Wrong Logged At');
		System.assertEquals(UserInfo.getUserId(), logEvent?.Running_User__c, 'Wrong Running_User__c');
		System.assertequals(1, logEvent?.Sequence__c, 'Wrong Sequence__c');
		System.assertNotEquals(null, logEvent?.Stack_Trace__c, 'Wrong Stack_Trace__c');
		System.assertEquals(
			System.Request.getCurrent().getRequestId(),
			logEvent?.Transaction_Id__c,
			'Wrong Transaction_Id__c'
		);
	}

	@IsTest
	static void shouldLogIfThresholdIsMet() {
		Logger.Settings = getActiveSettings(LoggingLevel.DEBUG);

		// All Logging Levels above the current threshold (or NONE) should not log
		for (
			LoggingLevel level : new List<LoggingLevel>{
				LoggingLevel.FINEST,
				LoggingLevel.FINER,
				LoggingLevel.FINE,
				LoggingLevel.NONE
			}
		) {
			Logger.log(level, 'This should not log');
			System.assertEquals(
				0,
				Logger.PendingLogs?.size(),
				level +
				' log posted outside of its defined threshold: ' +
				Logger.Threshold
			);
		}

		// All Logging Levels at or below the current threshold should log
		for (
			LoggingLevel level : new List<LoggingLevel>{
				LoggingLevel.DEBUG,
				LoggingLevel.INFO,
				LoggingLevel.WARN,
				LoggingLevel.ERROR
			}
		) {
			Logger.log(level, 'This should log');
		}
		System.assertEquals(
			4,
			Logger.PendingLogs?.size(),
			'Wrong # of pending logs: ' + JSON.serializePretty(Logger.PendingLogs)
		);
	}

	@IsTest
	static void shouldLogFromApi() {
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);
		Logger.LogInput input = new Logger.LogInput();
		input.logLevelName = LoggingLevel.FINEST.name();
		input.logMessage = 'Hello world!';
		List<Logger.LogInput> inputs = new List<Logger.LogInput>{ input };
		RestRequest request = new RestRequest();
		request.requestBody = Blob.valueOf(JSON.serialize(inputs));
		RestContext.request = request;

		Test.startTest();
		Logger.logFromApi();
		Test.stopTest();

		System.assertEquals(1, Logger.PublishedLogs?.size(), 'Wrong # of pending logs');
		System.assertEquals(input.logMessage, Logger.PublishedLogs[0].Message__c, 'Wrong message');
	}

	@IsTest
	static void shouldLogFromFlow() {
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);
		Logger.LogInput input = new Logger.LogInput();
		input.logLevelName = LoggingLevel.FINEST.name();
		input.logMessage = 'Hello world!';

		Test.startTest();
		Logger.logFromFlow(new List<Logger.LogInput>{ input });
		Test.stopTest();

		System.assertEquals(1, Logger.PublishedLogs?.size(), 'Wrong # of pending logs');
		System.assertEquals(input.logMessage, Logger.PublishedLogs[0].Message__c, 'Wrong message');
	}

	@IsTest
	static void shouldLogFromLightning() {
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);
		Logger.LogInput input = new Logger.LogInput();
		input.logLevelName = LoggingLevel.FINEST.name();
		input.logMessage = 'Hello world!';

		Test.startTest();
		Logger.logFromLightning(new List<Logger.LogInput>{ input });
		Test.stopTest();

		System.assertEquals(1, Logger.PublishedLogs?.size(), 'Wrong # of pending logs');
		System.assertEquals(input.logMessage, Logger.PublishedLogs[0].Message__c, 'Wrong message');
	}

	@IsTest
	static void shouldLogFromLevelSpecificMethod() {
		// Callers can use the level-specific overrides below for brevity
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);
		LoggingLevel currentLevel;
		Integer size = 0;

		Logger.error('Test Message');
		currentLevel = LoggingLevel.ERROR;
		size++;
		System.assertEquals(size, Logger.PendingLogs?.size(), currentLevel + ' not logged');
		System.assertEquals(String.valueOf(currentLevel), Logger.PendingLogs[size - 1].Level__c, 'Wrong Level');

		Logger.warn('Test Message');
		currentLevel = LoggingLevel.WARN;
		size++;
		System.assertEquals(size, Logger.PendingLogs?.size(), currentLevel + ' not logged');
		System.assertEquals(String.valueOf(currentLevel), Logger.PendingLogs[size - 1].Level__c, 'Wrong Level');

		Logger.info('Test Message');
		currentLevel = LoggingLevel.INFO;
		size++;
		System.assertEquals(size, Logger.PendingLogs?.size(), currentLevel + ' not logged');
		System.assertEquals(String.valueOf(currentLevel), Logger.PendingLogs[size - 1].Level__c, 'Wrong Level');

		Logger.debug('Test Message');
		currentLevel = LoggingLevel.DEBUG;
		size++;
		System.assertEquals(size, Logger.PendingLogs?.size(), currentLevel + ' not logged');
		System.assertEquals(String.valueOf(currentLevel), Logger.PendingLogs[size - 1].Level__c, 'Wrong Level');

		Logger.fine('Test Message');
		currentLevel = LoggingLevel.FINE;
		size++;
		System.assertEquals(size, Logger.PendingLogs?.size(), currentLevel + ' not logged');
		System.assertEquals(String.valueOf(currentLevel), Logger.PendingLogs[size - 1].Level__c, 'Wrong Level');

		Logger.finer('Test Message');
		currentLevel = LoggingLevel.FINER;
		size++;
		System.assertEquals(size, Logger.PendingLogs?.size(), currentLevel + ' not logged');
		System.assertEquals(String.valueOf(currentLevel), Logger.PendingLogs[size - 1].Level__c, 'Wrong Level');

		Logger.finest('Test Message');
		currentLevel = LoggingLevel.FINEST;
		size++;
		System.assertEquals(size, Logger.PendingLogs?.size(), currentLevel + ' not logged');
		System.assertEquals(String.valueOf(currentLevel), Logger.PendingLogs[size - 1].Level__c, 'Wrong Level');
	}

	@IsTest
	static void shouldIncludeApexClass() {
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);
		Type apexClass = Logger_Test.class;

		Test.startTest();
		Logger.error(apexClass, 'This is a test');
		Logger.warn(apexClass, 'This is a test');
		Logger.info(apexClass, 'This is a test');
		Logger.debug(apexClass, 'This is a test');
		Logger.fine(apexClass, 'This is a test');
		Logger.finer(apexClass, 'This is a test');
		Logger.finest(apexClass, 'This is a test');
		Test.stopTest();

		System.assertEquals(false, Logger.PendingLogs?.isEmpty(), 'No logs were generated');
		for (Log_Event__e log : Logger.PendingLogs) {
			System.assertEquals(String.valueOf(apexClass), log.Apex_Class__c, 'Wrong Apex Class value');
		}
	}

	@IsTest
	static void shouldNotLogInNewOrg() {
		// In a new org, without an org default Log_Setting__c,
		// Logger.Settings will be an empty object (no Level__c specified)
		// Calls to Logger.log() should not fail, but they won't log either
		Logger.Settings = new Log_Setting__c();
		Test.startTest();
		try {
			Logger.info('Testing 1234');
		} catch (Exception caughtError) {
			System.assert(false, 'An error was thrown: ' + caughtError);
		}
		Test.stopTest();

		System.assertEquals(0, Logger.PendingLogs?.size(), 'Log was generated with empty settings');
	}

	@IsTest
	static void shouldNotLogIfDisabled() {
		Logger.Settings = new Log_Setting__c(Enabled__c = false, Level__c = LoggingLevel.INFO.name());

		Test.startTest();
		for (LoggingLevel level : LoggingLevel.values()) {
			Logger.log(level, 'Logging for ' + level.name());
		}
		Test.stopTest();

		System.assertEquals(
			0,
			Logger.PendingLogs?.size(),
			'Log(s) were generated when Enabled set to false: ' + JSON.serializePretty(Logger.PendingLogs)
		);
	}

	@IsTest
	static void shouldLogAllIfThresholdIsFinest() {
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);

		Test.startTest();
		for (LoggingLevel level : LoggingLevel.values()) {
			Logger.log(level, 'Logging for ' + level.name());
		}
		Test.stopTest();

		// All except NONE and INTERNAL should generate a Log
		System.assertEquals(
			getValidLevels()?.size(),
			Logger.PendingLogs?.size(),
			'Wrong # of PendingLogs for FINEST: ' + JSON.serializePretty(Logger.PendingLogs)
		);
	}

	@IsTest
	static void shouldNotLogIfThresholdIsNone() {
		Logger.Settings = getActiveSettings(LoggingLevel.NONE);

		Test.startTest();
		for (LoggingLevel level : LoggingLevel.values()) {
			Logger.log(level, 'Logging for ' + level.name());
		}
		Test.stopTest();

		System.assertEquals(
			0,
			Logger.PendingLogs?.size(),
			'Log(s) were generated with a null LoggingLevel: ' + JSON.serializePretty(Logger.PendingLogs)
		);
	}

	@IsTest
	static void shouldNotLogIfNullLoggingLevel() {
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);

		Test.startTest();
		Logger.log(null, 'Hello world');
		Test.stopTest();

		System.assertEquals(0, Logger.PendingLogs?.size(), 'Log(s) were generated with a null LoggingLevel');
	}

	@IsTest
	static void shouldIncrementSequence() {
		// The Sequence__c field helps us to piece together a timeline;
		// It shows the order that log statements were generated in its Transaction_Id__c
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);
		for (Integer i = 0; i < 100; i++) {
			Integer logNumber = (i + 1);
			Logger.info('Test Message #' + logNumber);
			System.assertEquals(logNumber, Logger.PendingLogs?.size(), 'Wrong # of pending logs');
			System.assertEquals(logNumber, Logger.PendingLogs[i]?.Sequence__c, 'Wrong Sequence');
		}
	}

	@IsTest
	static void shouldExcludeSelfFromStackTrace() {
		// The Log Event's stack trace field should start from
		// where the Logger class is called from - not the Logger class itself
		Logger.Settings = getActiveSettings(LoggingLevel.FINEST);
		DmlMock dmlMock = (DmlMock) DatabaseLayer.setDmlEngine(new DmlMock());
		// Try logging from directly in the test class
		Logger.finest('Test Message');
		System.assertEquals(1, Logger.PendingLogs?.size(), 'Did not log');
		Log_Event__e event = Logger.PendingLogs[0];
		System.assert(
			event.Stack_Trace__c?.startsWithIgnoreCase('Class.Logger_Test.'),
			'Expected Stack Trace to start with "Class.Logger_Test." - Actual: "' +
			event.Stack_Trace__c +
			'"'
		);
		System.assert(
			event.Stack_Trace__c?.contains('Class.Logger.') == false,
			'Contains a stack trace line from the logger class: ' + event.Stack_Trace__c
		);
		// Try logging from another class
		new MyClass().logSomething();
		System.assertEquals(2, Logger.PendingLogs?.size(), 'Did not log from child class');
		event = Logger.PendingLogs[1];
		System.assert(
			event.Stack_Trace__c?.startsWithIgnoreCase('Class.Logger_Test.MyClass.'),
			'Expected Stack Trace to start with "Class.Logger_Test.MyClass." - Actual: "' +
			event.Stack_Trace__c +
			'"'
		);
		System.assert(
			event.Stack_Trace__c?.contains('Class.Logger.') == false,
			'Contains a stack trace line from the logger class: ' + event.Stack_Trace__c
		);
	}

	@IsTest
	static void shouldGenerateOrgDefaultSettingsIfNone() {
		// In a new org, no Custom Settings records exist by default. The Logger should still be able to operate
		// In this scenario, will create an inactive Settings record and set as Org Default
		delete [SELECT Id FROM Log_Setting__c]; // Just in case
		System.assertEquals(null, Log_Setting__c.getOrgDefaults()?.Id, 'Org Default settings still exists');
		Logger.info('Something'); // Any reference to the Logger class should do the trick
		Log_Setting__c defaults = Log_Setting__c.getOrgDefaults();
		System.assertNotEquals(null, defaults?.Id, 'Org Default settings still do not exist');
		System.assertEquals(LoggingLevel.NONE.name(), defaults?.Level__c, 'Wrong default level');
		System.assertEquals(false, defaults?.Enabled__c, 'Not inactive by default');
	}

	@IsTest
	static void shouldUpdateOrgDefaultSettingsIfInvalidLevel() {
		Log_Setting__c defaults = new Log_Setting__c(
			Level__c = 'lajsdflkjasdfljkasdfkljasdf',
			SetupOwnerId = UserInfo.getOrganizationId()
		);
		insert defaults;
		Logger.info('Something');
		defaults = Log_Setting__c.getOrgDefaults();
		System.assertEquals(LoggingLevel.NONE.name(), defaults?.Level__c, 'Wrong default level');
	}

	// **** HELPER **** //
	static Log_Setting__c getActiveSettings(LoggingLevel level) {
		return new Log_Setting__c(Enabled__c = true, Level__c = level?.name());
	}

	static Set<LoggingLevel> getValidLevels() {
		// INTERNAL and NONE logs are never published
		Set<LoggingLevel> validLevels = new Set<LoggingLevel>(LoggingLevel.values());
		validLevels.remove(LoggingLevel.NONE);
		validLevels.remove(LoggingLevel.INTERNAL);
		return validLevels;
	}

	// **** INNER **** //
	private class MyClass {
		private void logSomething() {
			Logger.log(LoggingLevel.FINEST, 'Test Message');
		}
	}
}