force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Represents a call to the logging framework. 
For each trigger instance, a &quot;Log Transaction&quot; record will be created. 
For each event instance, a &quot;Log&quot; record will be created.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message. Values are derived from Apex&apos;s standard LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>The Salesforce ID of the User which generated the log. This is always UserInfo.getUserId(). Maps to the &quot;Owner&quot; field on the &quot;Log Transaction&quot; object.</description>
    <label>Running User</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>The severity of the current log. Maps to the field of the same name on the &quot;Log&quot; object.</description>
    <label>Severity</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Optional field stores the general origin or the log file. Maps to the field of the same name on the &quot;Log&quot; object.
Possible values include:
- Apex
- Flow
- LWC
- Visualforce</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>In apex, displays the detailed origin of the log request. Maps to the field of the same name on the &quot;Log&quot; object.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>The Id of the execution window in which the event was published</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/Log_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Log Setting</label>
</CustomObject>

force-app/main/default/objects/Log_Setting__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When unchecked, no logs will be published regardless of the Level</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&quot;NONE&quot;</defaultValue>
    <description>Possible values correspond with the standard LoggingLevel Enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm
Unfortunately, picklists are not available for Custom Settings</description>
    <inlineHelpText>Possible values:
NONE: No logging.
ERROR: Error and exception logging.
WARN: Warning logging.
INFO: Informational logging.
DEBUG: User-specified debug logging.
FINE: High level of logging.
FINER: Higher level of logging than FINE.
FINEST: Highest level of logging.</inlineHelpText>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/fields/Max_Publish_Calls__c.field-meta.xml
<CustomField>
    <fullName>Max_Publish_Calls__c</fullName>
    <defaultValue>100</defaultValue>
    <description>Dictates the number of times logs can be published (via Logger.publish() or Logger.logAndPublish()) in a single transaction. Lower this number if you run into PublishImmediateDml Limits. 

Maximum is 150, 100 is recommended for most organizations. 

Note: Only the Organizational Defaults record will be referenced. Do not refer to this value on individual Settings records.</description>
    <inlineHelpText>Maximum is 150, 100 is recommended for most organizations. 

Note: Only the Organizational Defaults record will be referenced. Do not refer to this value on individual Settings records.</inlineHelpText>
    <label>Max Publish Calls</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Logger.cls
global without sharing class Logger {
    @TestVisible static Log_Setting__c settings;
    @TestVisible static LoggingLevel threshold;
    @TestVisible static Integer maxPublishCalls; 
    @TestVisible static List<Log_Event__e> pendingEvents = new List<Log_Event__e>();  
    @TestVisible static PlatformEventDml dmlEngine = new PlatformEventDml();
    
    // Indicates how severe something is. A log will only be published
    // if a log's logging level < the current user's "Level" threshold
    // LoggingLevel enum : https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm
    static final Map<LoggingLevel, Integer> SEVERITY_MATRIX = new Map<LoggingLevel, Integer>{
        LoggingLevel.NONE => 0,
        LoggingLevel.ERROR => 1, 
        LoggingLevel.WARN => 2,
        LoggingLevel.INFO => 3,
        LoggingLevel.DEBUG => 4,
        LoggingLevel.FINE => 5,
        LoggingLevel.FINER => 6,
        LoggingLevel.FINEST => 7
    };

    static {
        maxPublishCalls = Integer.valueOf(Log_Setting__c.getOrgDefaults().Max_Publish_Calls__c);
        maxPublishCalls = (maxPublishCalls != null) ? maxPublishCalls : 100; 
        settings = Log_Setting__c.getInstance(UserInfo.getUserId());
        threshold = loggingLevelValueOf(settings?.Level__c);
    }

    // **** PUBLIC **** //
    global static void log(LoggingLevel level, String message) {
        System.debug(level, message); 
        if (settings?.Enabled__c == true && clearsSeverityThreshold(level)) {
            Request context = Request.getCurrent(); 
            pendingEvents.add(new Log_Event__e(
                Message__c = message,
                Running_User__c = UserInfo.getUserId(),
                Severity__c = String.valueOf(level),
                Source__c = String.valueOf(context.getQuiddity()),
                Stack_Trace__c = getStackTrace(),
                Transaction_Id__c = context.getRequestId()           
            ));
        }
    }

    global static void log(String message) {
        // This will default the logging level to the current threshold
        log(threshold, message); 
    }

    global static void logAndPublish(LoggingLevel level, String message) {
        log(level, message); 
        publish(); 
    }

    global static void logAndPublish(String message) {
        logAndPublish(threshold, message); 
    }

    global static void publish() {
        Integer currentPublishCalls = Limits.getPublishImmediateDml();
        if (currentPublishCalls < maxPublishCalls) {
            dmlEngine.publish(pendingEvents); 
            pendingEvents.clear(); 
        }
    }

    global static void clear() {
        pendingEvents?.clear(); 
    }

    // **** PRIVATE **** //
    static Boolean clearsSeverityThreshold(LoggingLevel current) {
        // Returns true if the threshold != 'NONE',
        // and the current level has a lower severity number
        Integer thresholdSeverity = getSeverity(threshold); 
        Integer currentSeverity = getSeverity(current); 
        return 
            thresholdSeverity > 0 && 
            currentSeverity > 0 && 
            currentSeverity <= thresholdSeverity;
    }

    @TestVisible
    static LoggingLevel loggingLevelValueOf(String logLevel) {
        // Retrieve a LoggingLevel enum from a string value
        // Enum.valueOf() is supposed to do this,
        // but it will throw an exception if a null value 
        // or string that does not match an enum value is supplied
        LoggingLevel result; 
        try {
            result = LoggingLevel.valueOf(settings?.Level__c); 
        } catch (System.NoSuchElementException error) {
            result = LoggingLevel.NONE; 
        }
        return result; 
    }

    static Integer getSeverity(LoggingLevel logLevel) {
        Integer severity = SEVERITY_MATRIX.get(logLevel); 
        return (severity != null) ? severity : 0; 
    }

    static String getStackTrace() {
        // Generate an exception, grab its stack trace, and erase the elements that come from this class 
        return new LogException().sourceStackTrace(); 
    }

    // **** INNER **** //
    private class LogException extends Exception {
        private String sourceStackTrace() {
            List<String> stackTraceLines = new List<String>();
            for (String stackTraceLine : this.getStackTraceString().split('\n')) {
                // Do not include this class in the stack trace info
                if (!stackTraceLine?.startsWithIgnoreCase('Class.Logger.')) {
                    stackTraceLines.add(stackTraceLine); 
                }
            }
            return String.join(stackTraceLines, '\n');
        }
    }
}