force-app/main/default/objects/Log_Setting__c/Log_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Log Setting</label>
</CustomObject>

force-app/main/default/objects/Log_Setting__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When unchecked, no logs will be published regardless of the Level</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&quot;NONE&quot;</defaultValue>
    <description>Possible values correspond with the standard LoggingLevel Enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm
Unfortunately, picklists are not available for Custom Settings</description>
    <inlineHelpText>Possible values:
NONE: No logging.
ERROR: Error and exception logging.
WARN: Warning logging.
INFO: Informational logging.
DEBUG: User-specified debug logging.
FINE: High level of logging.
FINER: Higher level of logging than FINE.
FINEST: Highest level of logging.</inlineHelpText>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger/LogPublisher_Test.cls
@IsTest
private class LogPublisher_Test {
    @IsTest 
    static void shouldLog() {
        Logger.log('This is a test'); 

        Test.startTest();
        LogPublisher.invoke(); 
        Test.stopTest();

        System.assertEquals(1, Logger.PublishedLogs?.size(), 'Wrong # of Published Logs');
    }

    @IsTest 
    static void shouldDoNothingIfNoLogs() {
        Test.startTest();
        LogPublisher.invoke(); 
        Test.stopTest();

        System.assertEquals(0, Logger.PublishedLogs?.size(), 'Wrong # of Published Logs');
    }

    @IsTest 
    static void shouldDoNothingIfNotEnabled() {
        insert new Log_Setting__c(
            Enabled__c = false,
            SetupOwnerId = UserInfo.getUserId()
        );
        Logger.log('This is a test'); 

        Test.startTest();
        LogPublisher.invoke(); 
        Test.stopTest();

        System.assertEquals(0, Logger.PublishedLogs?.size(), 'Wrong # of Published Logs');
    }

    @TestSetup 
    static void setup() {
        // Create an org-wide default Log_Setting__c
        insert new Log_Setting__c(
            Enabled__c = true,
            Level__c = LoggingLevel.FINEST.name(),
            SetupOwnerId = UserInfo.getOrganizationId()
        );
    }
}