force-app/main/default/objects/Filter__mdt/Filter__mdt.object-meta.xml
<CustomObject>
    <label>Filter</label>
    <pluralLabel>Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Filter__mdt/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EQUALS</fullName>
                <default>true</default>
                <label>EQUALS</label>
            </value>
            <value>
                <fullName>NOT_EQUALS</fullName>
            </value>
            <value>
                <fullName>IN_COLLECTION</fullName>
            </value>
            <value>
                <fullName>NOT_IN_COLLECTION</fullName>
            </value>
            <value>
                <fullName>GREATER_THAN</fullName>
            </value>
            <value>
                <fullName>GREATER_OR_EQUAL</fullName>
            </value>
            <value>
                <fullName>LESS_THAN</fullName>
            </value>
            <value>
                <fullName>LESS_OR_EQUAL</fullName>
            </value>
            <value>
                <fullName>STARTS_WITH</fullName>
            </value>
            <value>
                <fullName>NOT_STARTS_WITH</fullName>
            </value>
            <value>
                <fullName>ENDS_WITH</fullName>
            </value>
            <value>
                <fullName>NOT_ENDS_WITH</fullName>
            </value>
            <value>
                <fullName>CONTAINS</fullName>
            </value>
            <value>
                <fullName>NOT_CONTAINS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/SObjectField__c.field-meta.xml
<CustomField>
    <fullName>SObjectField__c</fullName>
    <label>SObjectField</label>
    <metadataRelationshipControllingField>Filter__mdt.SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Filters</relationshipLabel>
    <relationshipName>Filters</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Text</type>
    <length>255</length>
    <required>true</required>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Use JSON syntax to indicate the data type, i.e.,
- Boolean: true
- Date: &quot;2000-01-01&quot;
- DateTime: &quot;2000-01-01T00:00:00Z&quot;
- Decimal: 1.0
- Integer: 1
- String: &quot;Hello World!&quot;</inlineHelpText>
    <label>Value</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/Rollup__mdt.object-meta.xml
<CustomObject>
    <description>Used to store rollup configuration in the org, instead of in apex code.
Each record represents a single Rollup.Request object, that is a configuration to update a single field on the parent object.</description>
    <label>Rollup</label>
    <pluralLabel>Rollups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When unchecked, the Rollup will not be run</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Calculation_Field__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Field__c</fullName>
    <inlineHelpText>The field on the Child SObject used to perform rollup calculations.
ex., SUM Opportunity.Amount
Not needed for COUNT-type rollups.</inlineHelpText>
    <label>Calculation Field</label>
    <metadataRelationshipControllingField>Rollup__mdt.Child_SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Calculation Fields</relationshipLabel>
    <relationshipName>Calculation_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Type__c</fullName>
    <defaultValue>&quot;AVG&quot;</defaultValue>
    <inlineHelpText>The type of calculation that will be applied during the rollup.
Either this field, or a Calculator Class Name must be provided.</inlineHelpText>
    <label>Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVG</fullName>
                <default>true</default>
                <label>AVG</label>
            </value>
            <value>
                <fullName>COUNT</fullName>
            </value>
            <value>
                <fullName>MAX</fullName>
            </value>
            <value>
                <fullName>MIN</fullName>
            </value>
            <value>
                <fullName>SUM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Calculator_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Calculator_Class_Name__c</fullName>
    <inlineHelpText>The name of an apex class which will handle the rollup calculation
This class must have a default constructor, and implement the Rollup.Calculator interface.
Either a Calculation Type, or this field must be provided.</inlineHelpText>
    <label>Calculator Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Child_SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Child_SObjectType__c</fullName>
    <inlineHelpText>The source SObject used in calculations</inlineHelpText>
    <label>Child SObjectType</label>
    <type>Text</type>
    <length>255</length>
    <required>true</required>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Parent_SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Parent_SObjectType__c</fullName>
    <inlineHelpText>The target SObjectType, where rollup results will be posted.</inlineHelpText>
    <label>Parent SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Parent Rollups</relationshipLabel>
    <relationshipName>Parent_Rollups</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <inlineHelpText>The API Name of the lookup field which points to the Parent SObjectType. 
This field&apos;s &quot;Child Relationship Name&quot; should match the Rollup&apos;s &quot;Child Relationship Name&quot;</inlineHelpText>
    <label>Relationship Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <inlineHelpText>The field on the Parent SObject where rollup results will be posted</inlineHelpText>
    <label>Target Field</label>
    <metadataRelationshipControllingField>Rollup__mdt.Parent_SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Target Fields</relationshipLabel>
    <relationshipName>Target Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/Rollup_Filter__mdt.object-meta.xml
<CustomObject>
    <description>Junction metadata relationship between Rollup and Filters</description>
    <label>Rollup Filter</label>
    <pluralLabel>Rollup Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When unchecked, the Rollup Filter will not be applied</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <referenceTo>Filter__mdt</referenceTo>
    <relationshipLabel>Rollup Filters</relationshipLabel>
    <relationshipName>Rollup_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Rollup__c.field-meta.xml
<CustomField>
    <fullName>Rollup__c</fullName>
    <label>Rollup</label>
    <referenceTo>Rollup__mdt</referenceTo>
    <relationshipLabel>Rollup Filters</relationshipLabel>
    <relationshipName>Rollup_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/RollupMetadataHelper_Test.cls
@IsTest 
private class RollupMetadataHelper_Test {
    @IsTest  
    static void shouldConstructSimpleRollupFromMdt() {
        Rollup__mdt rollupMdt = new Rollup__mdt(
            Calculation_Field__c = null, 
            Calculation_Type__c = 'COUNT',
            Child_SObjectType__c = 'Opportunity', 
            Parent_SObjectType__c = 'Account',
            Relationship_Field__c = 'AccountId',
            Target_Field__c = 'AnnualRevenue'
        );  

        Test.startTest();
        List<Rollup> rollups = new RollupMetadataHelper(new List<Rollup__mdt>{rollupMdt}).getRollups();
        Test.stopTest();

        System.assertEquals(1, rollups?.size(), 'Wrong # of rollups generated');
        Rollup rollup = rollups[0];
        System.assertEquals(Account.SObjectType, rollup.targetObject?.toSchemaType(), 'Wrong targetObject'); 
        System.assertEquals(1, rollup.relationships?.size(), 'Wrong # of relationships'); 
        Rollup.Relationship relationship = rollup.relationships?.values()[0];
        System.assertEquals(1, relationship?.requests?.size(), 'Wrong # of requests');
        Rollup.Request request = relationship?.requests?.values()[0];
        System.assertEquals(Account.AnnualRevenue, request?.targetField?.toSchemaType(), 'Wrong targetField');
        System.assertEquals(true, request?.calculator instanceOf CountCalculator, 'Wrong Calculator type');
        System.assertEquals(0, request?.filters?.size(), 'Wrong # of filters');
    }

    @IsTest 
    static void shouldConstructMultipleRequestsForSameRelationship() {
        List<Rollup__mdt> rollupMdts = new List<Rollup__mdt>{
            new Rollup__mdt(
                Active__c = true,
                Calculation_Field__c = null, 
                Calculation_Type__c = 'COUNT',
                Child_SObjectType__c = 'Opportunity', 
                Parent_SObjectType__c = 'Account',
                Relationship_Field__c = 'AccountId',
                Target_Field__c = 'AnnualRevenue'
            ),
            new Rollup__mdt(
                Active__c = true,
                Calculation_Field__c = null, 
                Calculation_Type__c = 'COUNT',
                Child_SObjectType__c = 'Opportunity', 
                Parent_SObjectType__c = 'Account',
                Relationship_Field__c = 'AccountId',
                Target_Field__c = 'NumberOfEmployees'
            ),
            new Rollup__mdt(
                Active__c = true,
                Calculation_Field__c = null, 
                Calculation_Type__c = 'COUNT',
                Child_SObjectType__c = 'Opportunity', 
                Parent_SObjectType__c = 'Account',
                Relationship_Field__c = 'AccountId',
                Target_Field__c = 'DunsNumber'
            )
        };

        Test.startTest();
        List<Rollup> rollups = new RollupMetadataHelper(rollupMdts).getRollups();
        Test.stopTest(); 

        System.assertEquals(1, rollups?.size(), 'Wrong # of rollups');
        Rollup rollup = rollups[0];
        System.assertEquals(Account.SObjectType, rollup.targetObject?.toSchemaType(), 'Wrong targetObject');
        System.assertEquals(1, rollup?.relationships?.size(), 'Wrong # of relationships');
        Rollup.Relationship relationship = rollup?.relationships.values()[0];
        System.assertEquals('Opportunities', relationship?.childRelationship?.toSchemaType()?.getRelationshipName(), 'Wrong relationship name');
        System.assertEquals(rollupMdts?.size(), relationship?.requests?.values()?.size(), 'Wrong # of requests');
    }

    @IsTest 
    static void shouldConstructMultipleRelationshipsForSameRollup() {
        List<Rollup__mdt> rollupMdts = new List<Rollup__mdt>{
            new Rollup__mdt(
                Active__c = true,
                Calculation_Field__c = null, 
                Calculation_Type__c = 'COUNT',
                Child_SObjectType__c = 'Opportunity', 
                Parent_SObjectType__c = 'Account',
                Relationship_Field__c = 'AccountId',
                Target_Field__c = 'AnnualRevenue'
            ),
            new Rollup__mdt(
                Active__c = true,
                Calculation_Field__c = 'CreatedDate', 
                Calculation_Type__c = 'COUNT',
                Child_SObjectType__c = 'Case', 
                Parent_SObjectType__c = 'Account',
                Relationship_Field__c = 'AccountId',
                Target_Field__c = 'AnnualRevenue'
            )
        };

        Test.startTest();
        List<Rollup> rollups = new RollupMetadataHelper(rollupMdts).getRollups();
        Test.stopTest();

        System.assertEquals(1, rollups?.size(), 'Wrong # of rollups generated');
        Rollup rollup = rollups[0];
        System.assertEquals(Account.SObjectType, rollup.targetObject?.toSchemaType(), 'Wrong targetObject'); 
        System.assertEquals(2, rollup.relationships?.size(), 'Wrong # of relationships'); 
        for (Rollup.Relationship relationship : rollup?.relationships.values()) {
            System.assertEquals(1, relationship?.requests?.values()?.size(), 'Wrong # of requests: ' + relationship?.requests?.values());
        }
    }

    @IsTest 
    static void shouldConstructMultipleRollups() {
        List<Rollup__mdt> rollupMdts = new List<Rollup__mdt>();
        rollupMdts.add(new Rollup__mdt(
            Active__c = true,
            Calculation_Field__c = null,
            Calculation_Type__c = 'COUNT',
            Child_SObjectType__c = 'Opportunity', 
            Parent_SObjectType__c = 'Account',
            Relationship_Field__c = 'AccountId',
            Target_Field__c = 'AnnualRevenue'
        ));
        rollupMdts.add(new Rollup__mdt(
            Active__c = true,
            Calculation_Field__c = null,
            Calculation_Type__c = 'COUNT',
            Child_SObjectType__c = 'Task',
            Parent_SObjectType__c = 'Lead',
            Relationship_Field__c = 'AccountId',
            Target_Field__c = 'NumberOfEmployees'
        ));

        Test.startTest();
        List<Rollup> rollups = new RollupMetadataHelper(rollupMdts).getRollups();
        Test.stopTest();

        System.assertEquals(2, rollups?.size(), 'Wrong # of rollups');
        for (Rollup rollup : rollups) {
            System.assertEquals(1, rollup?.relationships?.values().size(), 'Wrong # of relationships');
            System.assertEquals(1, rollup?.relationships?.values()[0]?.requests?.size(), 'Wrong # of requests');
        }
    }

    @IsTest 
    static void shouldConstructRollupWithFiltersFromMdt() {
        DatabaseLayer.setDmlEngine(new DmlMock());
        Rollup__mdt rollupMdt = new Rollup__mdt(
            Calculation_Field__c = null, 
            Calculation_Type__c = 'COUNT',
            Child_SObjectType__c = 'Opportunity', 
            Parent_SObjectType__c = 'Account',
            Relationship_Field__c = 'AccountId',
            Target_Field__c = 'AnnualRevenue'
        ); 
        Databaselayer.Dml.doInsert(rollupMdt);
        Filter__mdt filterMdt = new Filter__mdt(
            Operator__c = 'EQUALS',
            SObjectField__c = 'StageName',
            SObjectType__c = 'Opportunity',
            Value__c = '"Closed Won"'
        ); 
        Databaselayer.Dml.doInsert(filterMdt);
        Rollup_Filter__mdt rollupFilterMdt = new Rollup_Filter__mdt(Active__c = true);
        rollupFilterMdt = (Rollup_Filter__mdt) SObjectUtils.setLookupField(
            rollupFilterMdt, 
            Rollup_Filter__mdt.Filter__c, 
            filterMdt
        ); 
        Databaselayer.Dml.doInsert(rollupFilterMdt);
        rollupMdt = (Rollup__mdt) SObjectUtils.setRelatedList(
            rollupMdt, 
            SchemaUtils.getChildRelationship(Rollup_Filter__mdt.Rollup__c),
            new List<Rollup_Filter__mdt>{rollupFilterMdt}
        );

        Test.startTest();
        List<Rollup> rollups = new RollupMetadataHelper(new List<Rollup__mdt>{rollupMdt}).getRollups();
        Test.stopTest();
            
        System.assertEquals(1, rollups?.size(), 'Wrong # of rollups generated');
        Rollup rollup = rollups[0];
        System.assertEquals(Account.SObjectType, rollup.targetObject?.toSchemaType(), 'Wrong targetObject'); 
        System.assertEquals(1, rollup.relationships?.size(), 'Wrong # of relationships'); 
        Rollup.Relationship relationship = rollup.relationships?.values()[0];
        System.assertEquals(1, relationship?.requests?.values()?.size(), 'Wrong # of requests');
        Rollup.Request request = relationship?.requests?.values()[0];
        System.assertEquals(Account.AnnualRevenue, request?.targetField?.toSchemaType(), 'Wrong targetField');
        System.assertEquals(true, request?.calculator instanceOf CountCalculator, 'Wrong Calculator type');
        System.assertEquals(1, request?.filters?.size(), 'Wrong # of filters');
        Filter filterObj = request?.filters[0];
        System.assertEquals('StageName = \'Closed Won\'', request?.filters[0]?.toString(), 'Wrong filter');
    }

    @IsTest 
    static void shouldIgnoreInactiveFilters() {
        DatabaseLayer.setDmlEngine(new DmlMock());
        Rollup__mdt rollupMdt = new Rollup__mdt(
            Calculation_Field__c = null, 
            Calculation_Type__c = 'COUNT',
            Child_SObjectType__c = 'Opportunity', 
            Parent_SObjectType__c = 'Account',
            Relationship_Field__c = 'AccountId',
            Target_Field__c = 'AnnualRevenue'
        ); 
        Databaselayer.Dml.doInsert(rollupMdt);
        List<Filter__mdt> filterMdts = new List<Filter__mdt>{
            new Filter__mdt(
                Operator__c = 'EQUALS',
                SObjectField__c = 'StageName',
                SObjectType__c = 'Opportunity',
                Value__c = '"Closed Won"'
            ),
            new Filter__mdt(
                Operator__c = 'GREATER_THAN',
                SObjectField__c = 'Amount',
                SObjectTYpe__c = 'Opportunity',
                Value__c = '1000'
            ), 
            new Filter__mdt(
                Operator__c = 'NOT_EQUALS',
                SObjectField__c = 'CloseDate',
                SObjectType__c = 'Opportunity',
                Value__c = '"2022-01-01"'
            )
        };
        Databaselayer.Dml.doInsert(filterMdts);
        List<Rollup_Filter__mdt> rollupFilterMdts = new List<Rollup_Filter__mdt>();
        for (Integer i = 0; i < filterMdts?.size(); i++) {
            Filter__mdt filterMdt = filterMdts[i];
            Rollup_Filter__mdt rollupFilter = new Rollup_Filter__mdt(
                // Only 2/3 should be added to the request; 1st one is inactive
                Active__c = (i == 0) ? false : true
            );
            rollupFilter = (Rollup_Filter__mdt) SObjectUtils.setLookupField(rollupFilter, Rollup_Filter__mdt.Filter__c, filterMdt);
            rollupFilterMdts.add(rollupFilter);
        }
        Databaselayer.Dml.doInsert(rollupFilterMdts);
        rollupmdt = (Rollup__mdt) SObjectUtils.setRelatedList(
            rollupMdt, 
            SchemaUtils.getChildRelationship(Rollup_Filter__mdt.Rollup__c),
            rollupFilterMdts
        );

        Test.startTest();
        List<Rollup> rollups = new RollupMetadataHelper(new List<Rollup__mdt>{rollupMdt}).getRollups();
        Test.stopTest();

        System.assertEquals(1, rollups?.size(), 'Wrong # of rollups');
        System.assertEquals(1, rollups[0].relationships?.size(), 'Wrong # of relationships');
        System.assertEquals(1, rollups[0].relationships?.values()[0]?.requests?.size(), 'Wrong # of requests');
        System.assertEquals(rollupFilterMdts?.size() - 1, rollups[0].relationships?.values()[0].requests?.values()[0].filters?.size(), 'Wrong # of filters');
    }

    @IsTest 
    static void shouldUseCustomCalculator() {
        String calculatorClassName = 'CountCalculator';
        // Note: Normally, you'd define your own calculator class here
        Rollup__mdt rollupMdt = new Rollup__mdt(
            Calculation_Field__c = 'Amount',
            Calculator_Class_Name__c = calculatorClassName,
            Calculation_Type__c = null,
            Child_SObjectType__c = 'Opportunity', 
            Parent_SObjectType__c = 'Account',
            Relationship_Field__c = 'AccountId',
            Target_Field__c = 'AnnualRevenue'
        ); 

        Test.startTest();
        List<Rollup> rollups = new RollupMetadataHelper(new List<Rollup__mdt>{rollupMdt}).getRollups();
        Test.stopTest();

        System.assertEquals(1, rollups?.size(), 'Wrong # of Rollups');
        Rollup rollup = rollups[0];
        System.assertEquals(1, rollup?.relationships?.size(), 'Wrong # of relationships');
        Rollup.Relationship relationship = rollup?.relationships?.values()[0];
        System.assertEquals(1, relationship.requests?.size(), 'Wrong # of requests');
        Rollup.Request request = relationship?.requests?.values()[0];
        System.assertNotEquals(null, request?.calculator, 'Null calculator'); 
        System.assertEquals(true, request?.calculator instanceOf CountCalculator, 'Wrong calculator type');
    }

    @IsTest 
    static void shouldGetMdtRollupsForUseInTrigger() {
        // This demonstrates one potential use of this class; 
        // quickly/easily generating Rollups from MDT to run in a trigger
        DatabaseLayer.setDmlEngine(new DmlMock());
        DatabaseLayer.setQueryEngine(new SoqlMock.Factory());
        List<Rollup__mdt> rollupMdts = new List<Rollup__mdt>{
            new Rollup__mdt(
                Active__c = true,
                Calculation_Field__c = 'Amount',
                Calculation_Type__c = 'SUM',
                Child_SObjectType__c = 'Opportunity', 
                Parent_SObjectType__c = 'Account',
                Relationship_Field__c = 'AccountId',
                Target_Field__c = 'AnnualRevenue'
            ),
            new Rollup__mdt(
                Active__c = true,
                Calculation_Type__c = 'COUNT',
                Child_SObjectType__c = 'Opportunity', 
                Parent_SObjectType__c = 'Account',
                Relationship_Field__c = 'AccountId',
                Target_Field__c = 'NumberOfEmployees'
            )
        };
        Databaselayer.Dml.doInsert(rollupMdts);
        Filter__mdt oppIsClosedFilter = new Filter__mdt(
            Operator__c = 'EQUALS',
            SObjectField__c = 'IsClosed',
            SObjectType__c = 'Opportunity',
            Value__c = 'true'
        );
        Databaselayer.Dml.doInsert(oppIsClosedFilter);
        List<Rollup__mdt> rollupRecords = new List<Rollup__mdt>(); 
        for (Rollup__mdt rollupMdt : rollupMdts) {
            Rollup_Filter__mdt rollupFilter = new Rollup_Filter__mdt(Active__c = true);
            rollupFilter = (Rollup_Filter__mdt) SObjectUtils.setLookupField(rollupFilter, Rollup_Filter__mdt.Rollup__c, rollupMdt);
            rollupFilter = (Rollup_Filter__mdt) SObjectUtils.setLookupField(rollupFilter, Rollup_Filter__mdt.Filter__c, oppIsClosedFilter); 
            rollupRecords?.add((Rollup__mdt) SObjectUtils.setRelatedList(
                rollupMdt, 
                SchemaUtils.getChildRelationship(Rollup_Filter__mdt.Rollup__c),
                new List<Rollup_Filter__mdt>{rollupFilter}
            ));
        }
        RollupMetadataHelper.BaseQuery?.toMock()?.setMockResults(rollupRecords); 

        Test.startTest();
        Soql mdtQuery = RollupMetadataHelper.BaseQuery.whereFilters(new Filter(
            Rollup__mdt.Child_SObjectType__c,
            Filter.EQUALS,
            String.valueOf(Opportunity.SObjectType)
        ));
        List<Rollup__mdt> queryResults = (List<Rollup__mdt>) mdtQuery.run();
        List<Rollup> rollups = new RollupMetadataHelper(queryResults).getRollups(); 
        Test.stopTest();

        System.assertEquals(1, rollups?.size(), 'Wrong # of rollups'); 
        Rollup rollup = rollups[0];
        System.assertEquals(Account.SObjectType, rollup?.targetObject?.toSchemaType(), 'Wrong targetObject'); 
        System.assertEquals(1, rollup.relationships?.size(), 'Wrong # of relationships'); 
        Rollup.Relationship relationship = rollups[0].relationships?.values()[0];
        System.assertEquals('Opportunities', relationship?.childRelationship?.toSchemaType()?.getRelationshipName(), 'Wrong ChildRelationship');
        System.assertEquals(2, relationship?.requests?.values()?.size(), 'Wrong # of requests');
        for (Rollup.Request request : relationship?.requests?.values()) {
            System.assertEquals(1, request?.filters?.size(), 'Wrong # of filters');
            System.assertEquals('IsClosed = true', request?.filters[0]?.toString(), 'Wrong filter'); 
            if (request?.targetField?.toSchemaType() == Account.AnnualRevenue) {
                System.assertEquals(true, request?.calculator instanceOf SumCalculator, 'Wrong type of calculator: ' + TypeUtils.getTypeName(request?.calculator));
            } else if (request?.targetField?.toSchemaType() == Account.NumberOfEmployees) {
                System.assertEquals(true, request?.calculator instanceOf CountCalculator, 'Wrong type of calculator: ' + TypeUtils.getTypeName(request?.calculator));
            } else {
                System.assert(false, 'Unexpected target field: ' + request?.targetField + ': Request: ' + request);
            }
        }
    }

    @IsTest 
    static void shouldProvideBaseQuery() {
        Soql query = RollupMetadataHelper.BaseQuery; 
        List<Rollup__mdt> results; 

        Test.startTest(); 
        try {
            results = query.run(); 
        } catch (System.QueryException thrownError) {
            System.assert(false, 'Invalid query: ' + thrownError); 
        }
        Test.stopTest(); 

        // Note: We can't insert MDT directly from apex, so we can't guarantee results will be returned w/out mocking
        // This query should still return the same # of results as the below SOQL
        System.assertEquals([SELECT Id FROM Rollup__mdt WHERE Active__c = true]?.size(), results?.size(), 'Wrong # of results');
    }

    // **** HELPER **** // 
    @TestSetup 
    static void setup() {
        Account account = new Account(Name = 'Test Account');
        Databaselayer.Dml.doInsert(account); 
        List<Opportunity> opportunities = new List<Opportunity>(); 
        for (Integer i = 0; i < 3; i++) {
            opportunities.add(new Opportunity(
                AccountId = account.Id,
                Amount = 1000,
                CloseDate = Date.today(),
                Name = 'Test Opportunity #' + (i + 1),
                StageName = 'New'
            ));
        }
        Databaselayer.Dml.doInsert(opportunities); 
    }
}