force-app/main/default/objects/Filter__mdt/Filter__mdt.object-meta.xml
<CustomObject>
    <label>Filter</label>
    <pluralLabel>Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Filter__mdt/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EQUALS</fullName>
                <default>true</default>
                <label>EQUALS</label>
            </value>
            <value>
                <fullName>NOT_EQUALS</fullName>
            </value>
            <value>
                <fullName>IN_COLLECTION</fullName>
            </value>
            <value>
                <fullName>NOT_IN_COLLECTION</fullName>
            </value>
            <value>
                <fullName>GREATER_THAN</fullName>
            </value>
            <value>
                <fullName>GREATER_OR_EQUAL</fullName>
            </value>
            <value>
                <fullName>LESS_THAN</fullName>
            </value>
            <value>
                <fullName>LESS_OR_EQUAL</fullName>
            </value>
            <value>
                <fullName>STARTS_WITH</fullName>
            </value>
            <value>
                <fullName>NOT_STARTS_WITH</fullName>
            </value>
            <value>
                <fullName>ENDS_WITH</fullName>
            </value>
            <value>
                <fullName>NOT_ENDS_WITH</fullName>
            </value>
            <value>
                <fullName>CONTAINS</fullName>
            </value>
            <value>
                <fullName>NOT_CONTAINS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/SObjectField__c.field-meta.xml
<CustomField>
    <fullName>SObjectField__c</fullName>
    <label>SObjectField</label>
    <metadataRelationshipControllingField>Filter__mdt.SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Filters</relationshipLabel>
    <relationshipName>Filters</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Text</type>
    <length>255</length>
    <required>true</required>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Use JSON syntax to indicate the data type, i.e.,
- Boolean: true
- Date: &quot;2000-01-01&quot;
- DateTime: &quot;2000-01-01T00:00:00Z&quot;
- Decimal: 1.0
- Integer: 1
- String: &quot;Hello World!&quot;</inlineHelpText>
    <label>Value</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/Rollup__mdt.object-meta.xml
<CustomObject>
    <description>Used to store rollup configuration in the org, instead of in apex code.
Each record represents a single Rollup.Request object, that is a configuration to update a single field on the parent object.</description>
    <label>Rollup</label>
    <pluralLabel>Rollups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When unchecked, the Rollup will not be run</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Calculation_Field__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Field__c</fullName>
    <inlineHelpText>The field on the Child SObject used to perform rollup calculations.
ex., SUM Opportunity.Amount
Not needed for COUNT-type rollups.</inlineHelpText>
    <label>Calculation Field</label>
    <metadataRelationshipControllingField>Rollup__mdt.Child_SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Calculation Fields</relationshipLabel>
    <relationshipName>Calculation_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Type__c</fullName>
    <defaultValue>&quot;AVG&quot;</defaultValue>
    <inlineHelpText>The type of calculation that will be applied during the rollup.
Either this field, or a Calculator Class Name must be provided.</inlineHelpText>
    <label>Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVG</fullName>
                <default>true</default>
                <label>AVG</label>
            </value>
            <value>
                <fullName>COUNT</fullName>
            </value>
            <value>
                <fullName>MAX</fullName>
            </value>
            <value>
                <fullName>MIN</fullName>
            </value>
            <value>
                <fullName>SUM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Child_Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Name__c</fullName>
    <inlineHelpText>The name of the Schema.ChildRelationship that connects the Parent SObjectType to the Child SObjectType
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_Schema_ChildRelationship.htm</inlineHelpText>
    <label>Child Relationship Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Child_SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Child_SObjectType__c</fullName>
    <inlineHelpText>The source SObject used in calculations</inlineHelpText>
    <label>Child SObjectType</label>
    <type>Text</type>
    <length>255</length>
    <required>true</required>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Parent_SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Parent_SObjectType__c</fullName>
    <inlineHelpText>The target SObjectType, where rollup results will be posted.</inlineHelpText>
    <label>Parent SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Parent Rollups</relationshipLabel>
    <relationshipName>Parent_Rollups</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Relationship_Field__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Field__c</fullName>
    <inlineHelpText>The API Name of the lookup field which points to the Parent SObjectType. 
This field&apos;s &quot;Child Relationship Name&quot; should match the Rollup&apos;s &quot;Child Relationship Name&quot;</inlineHelpText>
    <label>Relationship Field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <inlineHelpText>The field on the Parent SObject where rollup results will be posted</inlineHelpText>
    <label>Target Field</label>
    <metadataRelationshipControllingField>Rollup__mdt.Parent_SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Target Fields</relationshipLabel>
    <relationshipName>Target Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/Rollup_Filter__mdt.object-meta.xml
<CustomObject>
    <description>Junction metadata relationship between Rollup and Filters</description>
    <label>Rollup Filter</label>
    <pluralLabel>Rollup Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When unchecked, the Rollup Filter will not be applied</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <referenceTo>Filter__mdt</referenceTo>
    <relationshipLabel>Rollup Filters</relationshipLabel>
    <relationshipName>Rollup_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Rollup__c.field-meta.xml
<CustomField>
    <fullName>Rollup__c</fullName>
    <label>Rollup</label>
    <referenceTo>Rollup__mdt</referenceTo>
    <relationshipLabel>Rollup Filters</relationshipLabel>
    <relationshipName>Rollup_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/InvocableRollup_Test.cls
@IsTest 
private class InvocableRollup_Test {
    @IsTest 
    static void shouldPerformSingleChildRollup() {
        setMocks(); 
        Rollup__mdt rollupMdt = getAccountRollup(Account.AnnualRevenue, false); 
        SoqlMock.setMockResults(RollupMetadataHelper.BASE_QUERY_KEY, new List<Rollup__mdt>{rollupMdt});

        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});
        DmlMock.resetHistory(); 

        InvocableRollup.Input input = new InvocableRollup.Input(); 
        input.timing = String.valueOf(InvocableRollup.Timing.SYNCHRONOUS);
        input.rollupContext = String.valueOf(InvocableRollup.RollupContext.CHILD); 
        input.records = account.Opportunities;
        input.rollup = rollupMdt;

        Test.startTest();
        InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
        Test.stopTest();

        System.assertEquals(true, Dml.Updated.containsRecord(account), 'Account was not updated'); 
        System.assertEquals(Decimal.valueOf(numOpps), account.AnnualRevenue, 'Wrong COUNT of Opportunities');
    }

    @IsTest 
    static void shouldPerformMultipleChildRollupsForSameParentSObject() {
        setMocks(); 
        Rollup__mdt withoutFilter = getAccountRollup(Account.AnnualRevenue, false); 
        Rollup__mdt withFilter = getAccountRollup(Account.NumberOfEmployees, true); 
        List<Rollup__mdt> rollups = new List<Rollup__mdt>{withFilter, withoutFilter};
        SoqlMock.setMockResults(RollupMetadataHelper.BASE_QUERY_KEY, rollups);

        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});
        DmlMock.resetHistory();

        InvocableRollup.Input input = new InvocableRollup.Input(); 
        input.timing = String.valueOf(InvocableRollup.Timing.SYNCHRONOUS);
        input.rollupContext = String.valueOf(InvocableRollup.RollupContext.CHILD); 
        input.records = account.Opportunities; 
        input.rollups = rollups;

        Test.startTest();
        InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
        Test.stopTest();

        System.assertEquals(true, Dml.Updated.containsRecord(account), 'Account was not updated'); 
        System.assertEquals(Decimal.valueOf(numOpps), account.AnnualRevenue, 'Wrong COUNT of Opportunities');
        System.assertEquals(Decimal.valueOf(numOpps) - 1, account.NumberOfEmployees, 'Wrong COUNT of Closed Won Opportunities');
    }

    @IsTest 
    static void shouldPerformAllChildRollups() {
        setMocks(); 
        Rollup__mdt withoutFilter = getAccountRollup(Account.AnnualRevenue, false); 
        Rollup__mdt withFilter = getAccountRollup(Account.NumberOfEmployees, true); 
        List<Rollup__mdt> rollups = new List<Rollup__mdt>{withFilter, withoutFilter};
        SoqlMock.setMockResults(RollupMetadataHelper.BASE_QUERY_KEY, rollups);
        
        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});
        DmlMock.resetHistory();

        InvocableRollup.Input input = new InvocableRollup.Input(); 
        input.timing = String.valueOf(InvocableRollup.Timing.SYNCHRONOUS);
        input.rollupContext = String.valueOf(InvocableRollup.RollupContext.CHILD); 
        input.records = account.Opportunities;
        // If no Rollup__mdts are defined, the method will query for & process all with a matching Parent_SObjectType__c
        input.rollup = null;
        input.rollups = null; 

        Test.startTest();
        InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
        Test.stopTest();

        System.assertEquals(true, Dml.Updated.containsRecord(account), 'Account was not updated'); 
        System.assertEquals(Decimal.valueOf(numOpps), account.AnnualRevenue, 'Wrong COUNT of Opportunities');
        System.assertEquals(Decimal.valueOf(numOpps) - 1, account.NumberOfEmployees, 'Wrong COUNT of Closed Won Opportunities');
    }

    @IsTest 
    static void shouldPerformSingleParentRollup() {
        setMocks(); 
        Rollup__mdt rollupMdt = getAccountRollup(Account.AnnualRevenue, false); 
        SoqlMock.setMockResults(RollupMetadataHelper.BASE_QUERY_KEY, new List<Rollup__mdt>{rollupMdt});

        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});
        DmlMock.resetHistory(); 

        InvocableRollup.Input input = new InvocableRollup.Input(); 
        input.timing = String.valueOf(InvocableRollup.Timing.SYNCHRONOUS);
        input.rollupContext = String.valueOf(InvocableRollup.RollupContext.PARENT); 
        input.record = account; 
        input.rollup = rollupMdt;

        Test.startTest();
        InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
        Test.stopTest();

        System.assertEquals(true, Dml.Updated.containsRecord(account), 'Account was not updated'); 
        System.assertEquals(Decimal.valueOf(numOpps), account.AnnualRevenue, 'Wrong COUNT of Opportunities');
    }

    @IsTest 
    static void shouldPerformMultipleParentRollups() {
        setMocks(); 
        Rollup__mdt withoutFilter = getAccountRollup(Account.AnnualRevenue, false); 
        Rollup__mdt withFilter = getAccountRollup(Account.NumberOfEmployees, true); 
        List<Rollup__mdt> rollups = new List<Rollup__mdt>{withFilter, withoutFilter};
        SoqlMock.setMockResults(RollupMetadataHelper.BASE_QUERY_KEY, rollups);

        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});
        DmlMock.resetHistory();

        InvocableRollup.Input input = new InvocableRollup.Input(); 
        input.timing = String.valueOf(InvocableRollup.Timing.SYNCHRONOUS);
        input.rollupContext = String.valueOf(InvocableRollup.RollupContext.PARENT); 
        input.record = account; 
        input.rollups = rollups;

        Test.startTest();
        InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
        Test.stopTest();

        System.assertEquals(true, Dml.Updated.containsRecord(account), 'Account was not updated'); 
        System.assertEquals(Decimal.valueOf(numOpps), account.AnnualRevenue, 'Wrong COUNT of Opportunities');
        System.assertEquals(Decimal.valueOf(numOpps) - 1, account.NumberOfEmployees, 'Wrong COUNT of Closed Won Opportunities');
    }

    @IsTest 
    static void shouldPerformAllParentRollups() {
        setMocks(); 
        Rollup__mdt withoutFilter = getAccountRollup(Account.AnnualRevenue, false); 
        Rollup__mdt withFilter = getAccountRollup(Account.NumberOfEmployees, true); 
        List<Rollup__mdt> rollups = new List<Rollup__mdt>{withFilter, withoutFilter};
        SoqlMock.setMockResults(RollupMetadataHelper.BASE_QUERY_KEY, rollups);
        
        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});
        DmlMock.resetHistory();

        InvocableRollup.Input input = new InvocableRollup.Input(); 
        input.timing = String.valueOf(InvocableRollup.Timing.SYNCHRONOUS);
        input.rollupContext = String.valueOf(InvocableRollup.RollupContext.PARENT); 
        input.record = account;
        // If no Rollup__mdts are defined, the method will query for & process all with a matching Parent_SObjectType__c
        input.rollup = null;
        input.rollups = null; 

        Test.startTest();
        InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
        Test.stopTest();

        System.assertEquals(true, Dml.Updated.containsRecord(account), 'Account was not updated'); 
        System.assertEquals(Decimal.valueOf(numOpps), account.AnnualRevenue, 'Wrong COUNT of Opportunities');
        System.assertEquals(Decimal.valueOf(numOpps) - 1, account.NumberOfEmployees, 'Wrong COUNT of Closed Won Opportunities');

    }

    @IsTest 
    static void shouldRunAsync() {
        setMocks(); 
        Rollup__mdt rollupMdt = getAccountRollup(Account.AnnualRevenue, false); 
        SoqlMock.setMockResults(RollupMetadataHelper.BASE_QUERY_KEY, new List<Rollup__mdt>{rollupMdt});

        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});
        DmlMock.resetHistory(); 

        InvocableRollup.Input input = new InvocableRollup.Input(); 
        // Since DML Behavior is ASYNC, everything will be done in a Queueable, later
        input.timing = String.valueOf(InvocableRollup.Timing.ASYNCHRONOUS);
        input.rollupContext = String.valueOf(InvocableRollup.RollupContext.PARENT); 
        input.record = account; 
        input.rollup = rollupMdt;

        Test.startTest();
        InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
        Test.stopTest();

        System.assertEquals(true, Dml.Updated.containsRecord(account), 'Account was not updated'); 
        System.assertEquals(Decimal.valueOf(numOpps), account.AnnualRevenue, 'Wrong COUNT of Opportunities');
    }

    @IsTest 
    static void shouldPerformRollupFromId() {
        setMocks(); 
        Rollup__mdt rollupMdt = getAccountRollup(Account.AnnualRevenue, false); 
        SoqlMock.setMockResults(RollupMetadataHelper.BASE_QUERY_KEY, new List<Rollup__mdt>{rollupMdt});

        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});
        DmlMock.resetHistory(); 

        InvocableRollup.Input input = new InvocableRollup.Input(); 
        // Since DML Behavior is ASYNC, everything will be done in a Queueable, later
        input.timing = String.valueOf(InvocableRollup.Timing.ASYNCHRONOUS);
        input.rollupContext = String.valueOf(InvocableRollup.RollupContext.PARENT); 
        input.recordId = account.Id;
        input.rollup = rollupMdt;

        Test.startTest();
        InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
        Test.stopTest();

        System.assertEquals(true, Dml.Updated.containsRecord(account), 'Account was not updated'); 
        System.assertEquals(Decimal.valueOf(numOpps), account.AnnualRevenue, 'Wrong COUNT of Opportunities');
    }

    @IsTest 
    static void shouldThrowErrorForInvalidMdtFields() {
        setMocks(); 
        Integer numOpps = 10; 
        Account account = getTestAccount(numOpps); 
        DatabaseLayer.DmlEngine.doInsert(account); 
        DmlMock.resetHistory(); 
        SoqlMock.setMockResults(Rollup.ROLLUP_QUERY, new List<Account>{account});

        Rollup__mdt template = new Rollup__mdt(
            Active__c = true,
            Calculation_Field__c = 'Amount',
            Calculation_Type__c = 'SUM',
            Child_Relationship_Name__c = 'Opportunities',
            Child_SObjectType__c = 'Opportunity', 
            Parent_SObjectType__c = 'Account',
            Relationship_Field__c = 'AccountId',
            Target_Field__c = 'AnnualRevenue'
        ); 
        List<Rollup__mdt> rollups = new List<Rollup__mdt>();
        for (SObjectField metadataField : new List<SObjectField>{
            Rollup__mdt.Calculation_Field__c,
            Rollup__mdt.Child_Relationship_Name__c,
            Rollup__mdt.Child_SObjectType__c,
            Rollup__mdt.Parent_SObjectType__c,
            Rollup__mdt.Relationship_Field__c,
            Rollup__mdt.Target_Field__c
        }) {
            Rollup__mdt withNullField = template.clone(); 
            withNullField.put(metadataField, null);
            rollups.add(withNullField); 

            Rollup__mdt withInvalidField = template.clone(); 
            withInvalidField.put(metadataField, 'asdf'); 
            rollups.add(withInvalidField); 
        }

        Test.startTest();
        for (Rollup__mdt rollup : rollups) {
            InvocableRollup.Input input = new InvocableRollup.Input();
            input.timing = String.valueOf(InvocableRollup.Timing.SYNCHRONOUS);
            input.rollupContext = String.valueOf(InvocableRollup.RollupContext.PARENT); 
            input.record = account; 
            input.rollup = rollup;

            Exception caughtError;
            try {
                InvocableRollup.invoke(new List<InvocableRollup.Input>{input});
            } catch (InvocableRollup.InvalidInputException thrownError) {
                caughtError = thrownError; 
            }
            System.assertNotEquals(null, caughtError, 'An error was not thrown/caught');
        }
        Test.stopTest();
    }

    // **** HELPER **** //
    static void setMocks() {
        DatabaseLayer.setDmlEngine(new DmlMock()); 
        DatabaseLayer.setQueryEngine(new SoqlMock.Factory()); 
    } 

    static Rollup__mdt getAccountRollup(SObjectField targetField, Boolean withFilters) {
        // Create the Rollup record
        Rollup__mdt rollupMdt = new Rollup__mdt(
            Active__c = true,
            Calculation_Field__c = null, 
            Calculation_Type__c = 'COUNT',
            Child_Relationship_Name__c = 'Opportunities',
            Child_SObjectType__c = 'Opportunity', 
            Parent_SObjectType__c = 'Account',
            Relationship_Field__c = 'AccountId',
            Target_Field__c = String.valueOf(targetField)
        );
        // Add Rollup Filters to the Rollup__mdt
        List<Rollup_Filter__mdt> rollupFilters = new List<Rollup_Filter__mdt>(); 
        if (withFilters) {
            Filter__mdt closedWonFilter = new Filter__mdt(
                Operator__c = 'EQUALS',
                SObjectField__c = 'StageName',
                SObjectType__c = 'Opportunity',
                Value__c = '"Closed Won"'
            );
            Rollup_Filter__mdt rollupFilter = (Rollup_Filter__mdt) ObjectUtils.setLookupField(
                new Rollup_Filter__mdt(Active__c = true),
                Rollup_Filter__mdt.Filter__c,
                closedWonFilter
            );
            rollupFilters.add(rollupFilter); 
        }
        return (Rollup__mdt) ObjectUtils.setReadOnlyField(
            rollupMdt, 
            'Rollup_Filters__r', 
            rollupFilters
        );
    }

    static Rollup__mdt getCampaignRollup(SObjectField targetField) {
        Rollup__mdt rollup = new Rollup__mdt(
            Active__c = true,
            Calculation_Field__c = null, 
            Calculation_Type__c = 'COUNT',
            Child_Relationship_Name__c = 'Opportunities',
            Child_SObjectType__c = 'Opportunity', 
            Parent_SObjectType__c = 'Campaign',
            Relationship_Field__c = 'CampaignId',
            Target_Field__c = String.valueOf(targetField)
        );
        return rollup; 
    }

    static Account getTestAccount(Integer numOpps) {
        Account account = new Account(Name = 'Test Account');
        Campaign campaign = new Campaign(Name = 'Test Campaign');
        DatabaseLayer.DmlEngine.doInsert(new List<SObject>{account, campaign}); 
        List<Opportunity> opportunities = new List<Opportunity>(); 
        for (Integer i = 0; i < numOpps; i++) {
            opportunities.add(new Opportunity(
                AccountId = account.Id,
                CampaignId = campaign.Id,
                Name = 'Test Opportunity #' + i,
                StageName = 'Closed Won'
            ));
        }
        // One of the opportunities will NOT be closed won
        opportunities[0].StageName = 'New';
        DatabaseLayer.DmlEngine.doInsert(opportunities); 
        return (Account) ObjectUtils.setReadOnlyField(account, 'Opportunities', opportunities); 
    }
}