force-app/main/default/objects/Filter__mdt/Filter__mdt.object-meta.xml
<CustomObject>
    <label>Filter</label>
    <pluralLabel>Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Filter__mdt/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EQUALS</fullName>
                <default>true</default>
                <label>EQUALS</label>
            </value>
            <value>
                <fullName>NOT_EQUALS</fullName>
            </value>
            <value>
                <fullName>IN_COLLECTION</fullName>
            </value>
            <value>
                <fullName>NOT_IN_COLLECTION</fullName>
            </value>
            <value>
                <fullName>GREATER_THAN</fullName>
            </value>
            <value>
                <fullName>GREATER_OR_EQUAL</fullName>
            </value>
            <value>
                <fullName>LESS_THAN</fullName>
            </value>
            <value>
                <fullName>LESS_OR_EQUAL</fullName>
            </value>
            <value>
                <fullName>STARTS_WITH</fullName>
            </value>
            <value>
                <fullName>NOT_STARTS_WITH</fullName>
            </value>
            <value>
                <fullName>ENDS_WITH</fullName>
            </value>
            <value>
                <fullName>NOT_ENDS_WITH</fullName>
            </value>
            <value>
                <fullName>CONTAINS</fullName>
            </value>
            <value>
                <fullName>NOT_CONTAINS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/SObjectField__c.field-meta.xml
<CustomField>
    <fullName>SObjectField__c</fullName>
    <label>SObjectField</label>
    <metadataRelationshipControllingField>Filter__mdt.SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>EntityParticle</referenceTo>
    <relationshipLabel>Filters</relationshipLabel>
    <relationshipName>Filters</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <type>Text</type>
    <length>255</length>
    <required>true</required>
</CustomField>

force-app/main/default/objects/Filter__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <inlineHelpText>Use JSON syntax to indicate the data type, i.e.,
- Boolean: true
- Date: &quot;2000-01-01&quot;
- DateTime: &quot;2000-01-01T00:00:00Z&quot;
- Decimal: 1.0
- Integer: 1
- String: &quot;Hello World!&quot;</inlineHelpText>
    <label>Value</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/Rollup__mdt.object-meta.xml
<CustomObject>
    <description>Used to store rollup configuration in the org, instead of in apex code.
Each record represents a single Rollup.Request object, that is a configuration to update a single field on the parent object.</description>
    <label>Rollup</label>
    <pluralLabel>Rollups</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When unchecked, the Rollup will not be run</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Calculation_Field__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Field__c</fullName>
    <inlineHelpText>The field on the Child SObject used to perform rollup calculations.
ex., SUM Opportunity.Amount
Not needed for COUNT-type rollups.</inlineHelpText>
    <label>Calculation Field</label>
    <metadataRelationshipControllingField>Rollup__mdt.Child_SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Calculation Fields</relationshipLabel>
    <relationshipName>Calculation_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Calculation_Type__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Type__c</fullName>
    <defaultValue>&quot;AVG&quot;</defaultValue>
    <inlineHelpText>The type of calculation that will be applied during the rollup.
Either this field, or a Calculator Class Name must be provided.</inlineHelpText>
    <label>Calculation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVG</fullName>
                <default>true</default>
                <label>AVG</label>
            </value>
            <value>
                <fullName>COUNT</fullName>
            </value>
            <value>
                <fullName>MAX</fullName>
            </value>
            <value>
                <fullName>MIN</fullName>
            </value>
            <value>
                <fullName>SUM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Calculator_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Calculator_Class_Name__c</fullName>
    <inlineHelpText>The name of an apex class which will handle the rollup calculation
This class must have a default constructor, and implement the Rollup.Calculator interface.
Either a Calculation Type, or this field must be provided.</inlineHelpText>
    <label>Calculator Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Child_Relationship_Name__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Name__c</fullName>
    <inlineHelpText>The name of the Schema.ChildRelationship that connects the Parent SObjectType to the Child SObjectType
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_class_Schema_ChildRelationship.htm</inlineHelpText>
    <label>Child Relationship Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Child_SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Child_SObjectType__c</fullName>
    <inlineHelpText>The source SObject used in calculations</inlineHelpText>
    <label>Child SObjectType</label>
    <type>Text</type>
    <length>255</length>
    <required>true</required>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Parent_SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Parent_SObjectType__c</fullName>
    <inlineHelpText>The target SObjectType, where rollup results will be posted.</inlineHelpText>
    <label>Parent SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Parent Rollups</relationshipLabel>
    <relationshipName>Parent_Rollups</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup__mdt/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <inlineHelpText>The field on the Parent SObject where rollup results will be posted</inlineHelpText>
    <label>Target Field</label>
    <metadataRelationshipControllingField>Rollup__mdt.Parent_SObjectType__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Target Fields</relationshipLabel>
    <relationshipName>Target Fields</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/Rollup_Filter__mdt.object-meta.xml
<CustomObject>
    <description>Junction metadata relationship between Rollup and Filters</description>
    <label>Rollup Filter</label>
    <pluralLabel>Rollup Filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>When unchecked, the Rollup Filter will not be applied</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <label>Filter</label>
    <referenceTo>Filter__mdt</referenceTo>
    <relationshipLabel>Rollup Filters</relationshipLabel>
    <relationshipName>Rollup_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Rollup_Filter__mdt/fields/Rollup__c.field-meta.xml
<CustomField>
    <fullName>Rollup__c</fullName>
    <label>Rollup</label>
    <referenceTo>Rollup__mdt</referenceTo>
    <relationshipLabel>Rollup Filters</relationshipLabel>
    <relationshipName>Rollup_Filters</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/RollupMetadataHelper.cls
public class RollupMetadataHelper {
    // In addition to defining Rollup objects on the fly in apex,
    // callers have the option of defining Rollup__mdt custom metadata objects
    // This class is used to convert Rollup__mdt => Rollup objects
    Map<SObjectType, Rollup> rollups = new Map<SObjectType, Rollup>();
    public static final Soql BASE_QUERY = RollupMetadataHelper.getBaseQuery(); 
    @TestVisible static final String BASE_QUERY_KEY = 'Rollup_MDT_Base_Query';
    static final Map<String, Type> CALCULATOR_BY_TOKEN = new Map<String, Type>{
        'AVG' => AvgCalculator.class,
        'COUNT' => CountCalculator.class,
        'MAX' => MaxCalculator.class,
        'MIN' => MinCalculator.class,
        'SUM' => SumCalculator.class
    };
    
    public RollupMetadataHelper(List<Rollup__mdt> rollupMdts) {
        for (Rollup__mdt rollupMdt : rollupMdts) {
            SObjectType objectType = Describes.getSObjectTypeByName(rollupMdt.Parent_SObjectType__c); 
            Rollup rollup = this.rollups.containsKey(objectType) 
                ? this.rollups.get(objectType) 
                : new Rollup(objectType);
            this.addRequest(rollup, rollupMdt); 
            this.rollups.put(objectType, rollup); 
        }
    }   

    public List<Rollup> getRollups() {
        return this.rollups?.values(); 
    }

    // **** PRIVATE **** //
    private void addRequest(Rollup rollup, Rollup__mdt rollupMdt) {
        rollup?.addRelationship(new Rollup.Relationship(Describes.getChildRelationship(
            rollupMdt?.Parent_SObjectType__c, 
            rollupMdt?.Child_Relationship_Name__c
        )).addRequest(new Rollup.Request(
            Describes.getSObjectFieldByName(
                rollupMdt?.Parent_SObjectType__c,
                rollupMdt?.Target_Field__c
            ),
            this.getCalculator(rollupMdt),
            this.getFilters(rollupMdt?.Rollup_Filters__r)
        )));
    }

    private Rollup.Calculator getCalculator(Rollup__mdt rollupMdt) {
        Schema.SObjectField calcField = Describes.getSObjectFieldByName(
            rollupMdt?.Child_SObjectType__c, 
            rollupMdt?.Calculation_Field__c
        ); 
        Type calcType = (String.isNotBlank(rollupMdt?.Calculator_Class_Name__c))
            ? Type.forName(rollupMdt?.Calculator_Class_Name__c)
            : RollupMetadataHelper.CALCULATOR_BY_TOKEN.get(rollupMdt?.Calculation_Type__c);
        return ((Rollup.Calculator) calcType?.newInstance())?.setCalcField(calcField); 
    } 

    private List<Filter> getFilters(List<Rollup_Filter__mdt> rollupFilters) {
        List<Filter> results = new List<Filter>(); 
        for (Rollup_Filter__mdt rollupFilter : rollupFilters) {
            if (rollupFilter.Active__c) {
                Filter__mdt filterMdt = rollupFilter.Filter__r; 
                results.add(new Filter(filterMdt)); 
            }
        }
        return results; 
    }

    static Soql getBaseQuery() {
        // Returns a base query which can be extended by callers.
        // It includes all necessary fields, and excludes inactive Filters/Rollups
        Filter activeFilter = new Filter('Active__c', Filter.EQUALS, true);
        SubQuery filtersQuery = (SubQuery) new SubQuery(Rollup__mdt.SObjectType, 'Rollup_Filters__r');
        filtersQuery.selectFields(Rollup_Filter__mdt.Active__c); 
        final String parentRelationship = Describes.getFieldDescribe(Rollup_Filter__mdt.Filter__c)?.getRelationshipName();
        for (SObjectField parentField : new List<SObjectField>{
            Filter__mdt.Operator__c, 
            Filter__mdt.SObjectField__c, 
            Filter__mdt.SObjectType__c,
            Filter__mdt.Value__c
        }) {
            String reference = parentRelationship + '.' + parentField; 
            filtersQuery.selectFields(reference);
        }
        return Databaselayer.Soql.newQuery(Rollup__mdt.SObjectType)
            .selectAll()
            .selectSubQuery(filtersQuery).whereFilters(activeFilter)
            .whereFilters(activeFilter)
            .setQueryKey(BASE_QUERY_KEY); 
    }
}