force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Log_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Log_Transaction__c</fullName>
    <description>The execution window where the log was generated</description>
    <label>Log Transaction</label>
    <referenceTo>Log_Transaction__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Salesforce User who generated the log.</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>The chosen LoggingLevel for the current log. 
Corresponds with the standard LoggingLevel enum: https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates the general location that the log was generated from</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>If the log was generated from apex, will contain information about how it was generated.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>An identifier unique to each apex transaction. Use this to group logs from the same transaction together.</description>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Represents a call to the logging framework. 
For each trigger instance, a &quot;Log Transaction&quot; record will be created. 
For each event instance, a &quot;Log&quot; record will be created.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>The Salesforce ID of the User which generated the log. This is always UserInfo.getUserId(). Maps to the &quot;Owner&quot; field on the &quot;Log Transaction&quot; object.</description>
    <label>Running User</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>The severity of the current log. Maps to the field of the same name on the &quot;Log&quot; object.</description>
    <label>Severity</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Optional field stores the general origin or the log file. Maps to the field of the same name on the &quot;Log&quot; object.
Possible values include:
- Apex
- Flow
- LWC
- Visualforce</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>In apex, displays the detailed origin of the log request. Maps to the field of the same name on the &quot;Log&quot; object.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>The Id of the execution window in which the event was published</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Transaction__c/Log_Transaction__c.object-meta.xml
<CustomObject>
    <description>Represents a single execution window in which logs are generated</description>
    <label>Log Transaction</label>
    <nameField>
        <displayFormat>LT-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Transaction__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Id of the apex transaction which generated the log file(s)</description>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LogGenerator_Test.cls
@IsTest
private class LogGenerator_Test {
    @IsTest 
    static void shouldGenerateOneTransactionRecordPerTransactionId() { 
        Set<String> transactionIds = new Set<String>(); 
        List<Log_Event__e> logEvents = new List<Log_Event__e>(); 
        // Generate 200 transaction Ids - should generate 200 Log Transaction records
        for (Integer i = 0; i < 200; i++) {
            String transactionId = 'Transaction #' + Crypto.getRandomInteger() + '_' + i;
            transactionIds.add(transactionId);
            // Add one event per transactionId
            logEvents.add(new Log_Event__e(
                Message__c = 'Testing 123',
                Running_User__c = UserInfo.getUserId(),
                Severity__c = 'FINEST',
                Transaction_Id__c = transactionId
            ));

        }

        Test.startTest();
        DmlMock dmlMock = new DmlMock(); 
        LogGenerator generator = new LogGenerator(logEvents); 
        DatabaseLayer.setDmlEngine(dmlMock); 
        generator.generateLogs(); 
        Test.stopTest(); 
        
        List<Log_Transaction__c> logTransactions = dmlMock.upserted.getRecords(Log_Transaction__c.SObjectType); 
        System.assertEquals(transactionIds?.size(), logTransactions?.size(), 'Wrong # of Log Transactions generated');
        List<Log__c> logRecords = dmlMock.inserted.getRecords(Log__c.SObjectType); 
        System.assertEquals(transactionIds?.size(), logRecords?.size(), 'Wrong # of Log Records generated. DmlMock: ' + JSON.serializePretty(dmlMock)); 
    }

    @IsTest 
    static void shouldGenerateOneLogRecordPerEvent() {
        Request context = Request.getCurrent(); 
        List<Log_Event__e> logEvents = new List<Log_Event__e>();
        for (Integer i = 0; i < 200; i++) {
            logEvents.add(new Log_Event__e(
                Message__c = 'Testing 123',
                Running_User__c = UserInfo.getUserId(),
                Severity__c = String.valueOf(LoggingLevel.FINEST),
                Source__c = String.valueOf(context.getQuiddity()),
                Stack_Trace__c = 'n/a',
                Transaction_Id__c = context.getRequestId()           
            ));
        }
        
        Test.startTest();
        DmlMock dmlMock = new DmlMock(); 
        LogGenerator generator = new LogGenerator(logEvents); 
        DatabaseLayer.setDmlEngine(dmlMock);
        generator.generateLogs(); 
        Test.stopTest(); 

        List<Log_Transaction__c> logTransactions = (List<Log_Transaction__c>) 
        dmlMock.upserted.getRecords(Log_Transaction__c.SObjectType);
        System.assertEquals(1, logTransactions?.size(), 'Wrong number of transactions inserted');
        Log_Transaction__c logTransaction = logTransactions[0]; 
        System.assertEquals(UserInfo.getUserId(), logTransaction.OwnerId, 'Wrong running user'); 
        System.assertEquals(context.getRequestId(), logTransaction.Transaction_Id__c, 'Wrong Transaction Id');

        List<Log__c> logs = (List<Log__c>) dmlMock.inserted.getRecords(Log__c.SObjectType);
        for (Log__c log : logs) {
            System.assertEquals('Testing 123', log.Message__c, 'Wrong Message');
            System.assertEquals('FINEST', log.Severity__c, 'Wrong Severity');
            System.assertEquals(String.valueOf(context.getQuiddity()), log.Source__c, 'Wrong Source');
            System.assertEquals('n/a', log.Stack_Trace__c, 'Wrong Stack Trace');
        }
    }
}