force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>The nam of the Apex Class which generated the log. Since Exception.getStackTraceString() does not work in managed packages, this can be used to give at least some context of where the log was generated.</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Details the current execution context when the log was generated.
Displays a System.Quiddity value: 
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</description>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message. Values are derived from Apex&apos;s standard LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Logged_At__c.field-meta.xml
<CustomField>
    <fullName>Logged_At__c</fullName>
    <description>Shows when the log was generated. 
Different from Created Date, which shows when the log was published.</description>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Salesforce User who generated the log.</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <inlineHelpText>Indicates the order in which logs in the same transaction were inserted (beginning with 1).</inlineHelpText>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>If the log was generated from apex, will contain information about how it was generated.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>An identifier unique to each apex transaction. Use this to group logs from the same transaction together.</description>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Represents a call to the logging framework. 
For each trigger instance, a &quot;Log Transaction&quot; record will be created. 
For each event instance, a &quot;Log&quot; record will be created.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>The name of the apex class which generated the log. Since Exception.getStackTraceString() does not work in managed packages, this can be used to give at least some context of where the log was generated.</description>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Details the current execution context when the log was generated.
Displays a System.Quiddity value:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_Quiddity.htm#topic-title</description>
    <label>Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message. Values are derived from Apex&apos;s standard LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Logged_At__c.field-meta.xml
<CustomField>
    <fullName>Logged_At__c</fullName>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>The Salesforce ID of the User which generated the log. This is always UserInfo.getUserId(). Maps to the &quot;Owner&quot; field on the &quot;Log Transaction&quot; object.</description>
    <label>Running User</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Indicates the order in which logs in the same transaction were inserted (beginning with 1).</description>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>In apex, displays the detailed origin of the log request. Maps to the field of the same name on the &quot;Log&quot; object.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>The Id of the execution window in which the event was published</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/Log_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Log Setting</label>
</CustomObject>

force-app/main/default/objects/Log_Setting__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When unchecked, no logs will be published regardless of the Level</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&quot;NONE&quot;</defaultValue>
    <description>Possible values correspond with the standard LoggingLevel Enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm
Unfortunately, picklists are not available for Custom Settings</description>
    <inlineHelpText>Possible values:
NONE: No logging.
ERROR: Error and exception logging.
WARN: Warning logging.
INFO: Informational logging.
DEBUG: User-specified debug logging.
FINE: High level of logging.
FINER: Higher level of logging than FINE.
FINEST: Highest level of logging.</inlineHelpText>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger/Logger.cls
@RestResource(urlMapping='/log')
global without sharing abstract class Logger {
	static final Integer MAX_LENGTH = Log__c.Message__c.getDescribe()?.getLength();
	static Integer Sequence = 1;

	@TestVisible
	static List<Log_Event__e> PendingLogs = new List<Log_Event__e>();

	@TestVisible
	static List<Log_Event__e> PublishedLogs = new List<Log_Event__e>();

	@TestVisible
	static Log_Setting__c Settings = Logger.getLogSettings();

	@TestVisible
	static LoggingLevel Threshold {
		get {
			Boolean matchesSettings = Logger.Threshold?.name()?.equalsIgnoreCase(Logger.Settings?.Level__c);
			if (matchesSettings != true) {
				LoggingLevel newLevel = (LoggingLevel) EnumUtils.valueOf(Settings?.Level__c, LoggingLevel.class);
				Logger.Threshold = (newLevel != null) ? newLevel : LoggingLevel.NONE;
			}
			return Logger.Threshold;
		}
		private set;
	}

	// **** GLOBAL **** //
	@HttpPost
	global static void logFromApi() {
		// Exposes the logger to external solutions
		try {
			String requestBody = RestContext.request?.requestBody?.toString();
			List<LogInput> logInputs = (List<LogInput>) JSON.deserialize(requestBody, List<LogInput>.class);
			Logger.logFromExternalSource(logInputs);
			RestContext.response.statusCode = 200;
		} catch (Exception error) {
			RestContext.response.statusCode = 500;
			RestContext.response.responseBody = Blob.valueOf(
				JSON.serialize(new Map<String, String>{
					 'message' => String.valueOf(error) 
				})
			);
		}
	}

	@InvocableMethod(category='Logging' configurationEditor='c-cpe-logger' label='Post to Log')
	global static void logFromFlow(List<LogInput> logInputs) {
		// Exposes the logger to Flows
		Logger.logFromExternalSource(logInputs);
	}

	@AuraEnabled
	global static void logFromLightning(List<LogInput> logInputs) {
		// Exposes the logger to Aura Components & LWCs
		Logger.logFromExternalSource(logInputs);
	}

	// **** PUBLIC **** //
	public static void publish() {
		Logger.PublishedLogs.addAll(Logger.PendingLogs);
		DatabaseLayer.Dml.doPublish(Logger.PendingLogs);
		Logger.PendingLogs.clear();
	}

	public static void log(LoggingLevel level, Type apexClass, Object messageObj) {
		// Note: Since Exception.getStackTraceString() returns null in managed packages,
		// callers can use the optional `apexClass` param for rudimentary stack tracing
		if (Logger.isEnabled(level)) {
			System.debug(level, messageObj);
			Logger.PendingLogs.add(
				new Log_Event__e(
					Apex_Class__c = String.valueOf(apexClass),
					Context__c = System.Request.getCurrent().getQuiddity()?.name(),
					Level__c = level?.name(),
					Logged_At__c = DateTime.now(),
					Message__c = String.valueOf(messageObj)?.abbreviate(MAX_LENGTH),
					Running_User__c = UserInfo.getUserId(),
					Sequence__c = Logger.Sequence++,
					Stack_Trace__c = Logger.getStackTrace()?.abbreviate(MAX_LENGTH),
					Transaction_Id__c = System.Request.getCurrent()?.getRequestId()
				)
			);
		}
	}

	public static void log(LoggingLevel level, Object message) {
		Logger.log(level, null, message);
	}

	public static void log(Object message) {
		// Defaults to FINEST
		Logger.finest(message);
	}

	public static void error(Type apexClass, Object message) {
		Logger.log(LoggingLevel.ERROR, apexClass, message);
	}

	public static void error(Object message) {
		Logger.error(null, message);
	}

	public static void warn(Type apexClass, Object message) {
		Logger.log(LoggingLevel.WARN, apexClass, message);
	}

	public static void info(Type apexClass, Object message) {
		Logger.log(LoggingLevel.INFO, apexClass, message);
	}

	public static void info(Object message) {
		Logger.info(null, message);
	}

	public static void warn(Object message) {
		Logger.warn(null, message);
	}

	public static void debug(Type apexClass, Object message) {
		Logger.log(LoggingLevel.DEBUG, apexClass, message);
	}

	public static void debug(Object message) {
		Logger.debug(null, message);
	}

	public static void fine(Type apexClass, Object message) {
		Logger.log(LoggingLevel.FINE, apexClass, message);
	}

	public static void fine(Object message) {
		Logger.fine(null, message);
	}

	public static void finer(Type apexClass, Object message) {
		Logger.log(LoggingLevel.FINER, apexClass, message);
	}

	public static void finer(Object message) {
		Logger.finer(null, message);
	}

	public static void finest(Type apexClass, Object message) {
		Logger.log(LoggingLevel.FINEST, apexClass, message);
	}

	public static void finest(Object message) {
		Logger.finest(null, message);
	}

	// **** PRIVATE **** //
	@TestVisible
	static Log_Setting__c getLogSettings() {
		// Returns a Custom Setting record that corresponds to the running user/their profile/their organization
		Log_Setting__c logSettings = Log_Setting__c.getInstance();
		LoggingLevel level = (LoggingLevel) EnumUtils.valueOf(logSettings?.Level__c, LoggingLevel.class);
		if (level == null) {
			// Either no org defaults exist, or it has a missing/invalid Level__c
			// If this happens, upsert a valid settings record and set as org default
			Log_Setting__c defaultSettings = Log_Setting__c.getOrgDefaults();
			defaultSettings.Enabled__c = (defaultSettings.Enabled__c) ? defaultSettings.Enabled__c : false;
			defaultSettings.Level__c = LoggingLevel.NONE?.name();
			defaultSettings.SetupOwnerId = UserInfo.getOrganizationId();
			upsert defaultSettings;
			logSettings = defaultSettings;
		}
		return logSettings;
	}

	static void logFromExternalSource(List<LogInput> logInputs) {
		for (LogInput logInput : logInputs) {
			logInput.log();
		}
		Logger.publish();
	}

	static Boolean isEnabled(LoggingLevel currentLevel) {
		// Returns TRUE if logging is enabled, and the current level is
		// as/more severe than the minimum threshold specified in Custom Settings.
		// This is done to mimick the way traditional debug logs are set up in Salesforce.
		// Severity is indicated by the LoggingLevel enum's ordinal(), in order:
		// NONE(0), INTERNAL(1), FINEST(2), FINER(3), FINE(4), DEBUG(5), INFO(6), WARN(7), ERROR(8)
		Integer thresholdSeverity = (Logger.Threshold != null) ? Logger.Threshold?.ordinal() : 0;
		Integer currentSeverity = (currentLevel != null) ? currentLevel?.ordinal() : 0;
		Boolean results =
			Logger.Settings?.Enabled__c == true &&
			thresholdSeverity > 0 && // Prevent logging when Logger.Threshold == NONE
			currentSeverity >= thresholdSeverity;
		return results;
	}

	static String getStackTrace() {
		return new LogException().sourceStackTrace();
	}

	// **** INNER **** //
	global class LogInput {
		@InvocableVariable
		global String logLevelName;

		@InvocableVariable
		global String logMessage;

		public void log() {
			LoggingLevel level = (LoggingLevel) EnumUtils.valueOf(logLevelName, LoggingLevel.class);
			if (level != null) {
				Logger.log(level, logMessage);
			}
		}
	}

	private class LogException extends Exception {
		private String sourceStackTrace() {
			List<String> stackTraceLines = new List<String>();
			for (String stackTraceLine : this.getStackTraceString().split('\n')) {
				// Do not include this class in the stack trace info
				final String loggerPrefix = 'Class.' + String.valueOf(Logger.class) + '.';
				if (!stackTraceLine?.startsWith(loggerPrefix)) {
					stackTraceLines.add(stackTraceLine);
				}
			}
			return String.join(stackTraceLines, '\n');
		}
	}
}