force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{00000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Log_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Log_Transaction__c</fullName>
    <description>The execution window where the log was generated</description>
    <label>Log Transaction</label>
    <referenceTo>Log_Transaction__c</referenceTo>
    <relationshipLabel>Logs</relationshipLabel>
    <relationshipName>Log</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Salesforce User who generated the log.</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>The chosen LoggingLevel for the current log. 
Corresponds with the standard LoggingLevel enum: https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Indicates the general location that the log was generated from</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Visualforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>If the log was generated from apex, will contain information about how it was generated.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>An identifier unique to each apex transaction. Use this to group logs from the same transaction together.</description>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Represents a call to the logging framework. 
For each trigger instance, a &quot;Log Transaction&quot; record will be created. 
For each event instance, a &quot;Log&quot; record will be created.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <description>The Salesforce ID of the User which generated the log. This is always UserInfo.getUserId(). Maps to the &quot;Owner&quot; field on the &quot;Log Transaction&quot; object.</description>
    <label>Running User</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>The severity of the current log. Maps to the field of the same name on the &quot;Log&quot; object.</description>
    <label>Severity</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Optional field stores the general origin or the log file. Maps to the field of the same name on the &quot;Log&quot; object.
Possible values include:
- Apex
- Flow
- LWC
- Visualforce</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>In apex, displays the detailed origin of the log request. Maps to the field of the same name on the &quot;Log&quot; object.</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <description>The Id of the execution window in which the event was published</description>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Transaction__c/Log_Transaction__c.object-meta.xml
<CustomObject>
    <description>Represents a single execution window in which logs are generated</description>
    <label>Log Transaction</label>
    <nameField>
        <displayFormat>LT-{00000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Transaction__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The Id of the apex transaction which generated the log file(s)</description>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LogGenerator.cls
public without sharing class LogGenerator {
    final List<Log_Event__e> events; 

    public LogGenerator(List<Log_Event__e> events) {
        this.events = events;
    }

    public void generateLogs() {
        // Wrap LogEvents with the same TransactionId, and Map by their TransactionId
        Map<String, LogGroup> logGroups = this.groupLogsByTransactionId(); 
        // Generate & upsert a Log_Transaction__c record for each unique TransactionId
        List<Log_Transaction__c> logTransactions = this.generateLogTransactions(logGroups.values()); 
        DatabaseLayer.DmlEngine.doUpsert(logTransactions, Log_Transaction__c.Transaction_Id__c); 
        // Generate & Insert a Log__c record for each Log Event
        List<Log__c> logRecords = this.generateLogs(logGroups.values());
        DatabaseLayer.DmlEngine.doInsert(logRecords); 
    }

    private Map<String, LogGroup> groupLogsByTransactionId() {
        Map<String, LogGroup> logGroups = new Map<String, LogGroup>();
        for (Log_Event__e event : events) {
            String transactionId = event.Transaction_Id__c; 
            LogGroup logGroup = (logGroups.containsKey(transactionId)) 
                ? logGroups.get(transactionId) : new LogGroup(transactionId);
            logGroup.addEvent(event); 
            logGroups.put(transactionId, logGroup); 
        }
        return logGroups; 
    }

    private List<Log_Transaction__c> generateLogTransactions(List<LogGroup> logGroups) {
        List<Log_Transaction__c> logTransactions = new List<Log_Transaction__c>();
        for (LogGroup logGroup : logGroups) {
            logTransactions.add(logGroup.generateTransactionRecord());
        }
        return logTransactions; 
    }

    private List<Log__c> generateLogs(List<LogGroup> logGroups) {
        List<Log__c> logRecords = new List<Log__c>();
        for (LogGroup logGroup : logGroups) {
            logRecords.addAll(logGroup.generateLogRecords()); 
        }
        return logRecords;
    }

    private class LogGroup {
        final String transactionId; 
        List<Log_Event__e> logEvents = new List<Log_Event__e>();
        Log_Transaction__c logTransaction; 
        List<Log__c> logRecords = new List<Log__c>();

        private LogGroup(String transactionId) {
            this.transactionId = transactionId;
        }

        private void addEvent(Log_Event__e event) {
            this.logEvents.add(event); 
        }

        private Log_Transaction__c generateTransactionRecord() {
            this.logTransaction = new Log_Transaction__c(
                OwnerId = this.getRunningUserId(),
                Transaction_Id__c = this.transactionId
            );
            return this.logTransaction; 
        }

        private Id getRunningUserId() {
            return (this.logEvents?.isEmpty() == false) 
                ? this.logEvents[0]?.Running_User__c : UserInfo.getUserId();
        }

        private List<Log__c> generateLogRecords() {
            List<Log__c> logRecords = new List<Log__c>();
            for (Log_Event__e event : this.logEvents) {
                this.logRecords.add(new Log__c(
                    Log_Transaction__c = this.logTransaction.Id,
                    Message__c = event.Message__c,
                    Severity__c = event.Severity__c, 
                    Source__c = event.Source__c,
                    Stack_Trace__c = event.Stack_Trace__c
                ));
            }
            return this.logRecords;
        }
    }
}