force-app/main/default/objects/Garbage_Collection_Job__mdt/Garbage_Collection_Job__mdt.object-meta.xml
<CustomObject>
    <description>Each record will create a batch class to delete records of the specified SObjectType</description>
    <label>Garbage Collection Job</label>
    <pluralLabel>Garbage Collection Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Garbage_Collection_Jobs</relationshipLabel>
    <relationshipName>Garbage_Collection_Jobs</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/SOQL_Filter__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Filter__c</fullName>
    <description>Sets the WHERE clause for the Garbage Collector batch&apos;s QueryLocator
For more complex filtering, consider referencing an GarbageCollector instance in the &quot;Apex Class Name&quot; field instaed.</description>
    <inlineHelpText>Format: &quot;SELECT Id FROM SObject WHERE ({Your input here})&quot;
ex. &quot;IsClosed = true AND CreatedDate &gt; LAST_N_DAYS:365&quot;</inlineHelpText>
    <label>SOQL Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GarbageCollection/GarbageCollectorSoql.cls
public without sharing class GarbageCollectorSoql extends GarbageCollector {
	// Note: Because this is the "default" implementation,
	// I'd normally keep this class in the same file as its parent
	// However, Salesforce does not allow Database.Batchable to be applied to inner types
	@TestVisible
	String soql = 'SELECT Id FROM {0} WHERE ({1})';

	public GarbageCollectorSoql(Garbage_Collection_Job__mdt job) {
		String query = String.format(this.soql, new List<String>{ job?.SObjectType__c, job?.SOQL_Filter__c });
		this.soql = String.escapeSingleQuotes(query); 
	}

	public Database.QueryLocator start(Database.BatchableContext context) {
		try {
			return Database.getQueryLocator(soql);
		} catch (System.QueryException queryError) {
			String message = queryError + '\nQuery:\n' + this.soql; 
			Logger.error(message); 
			Logger.publish();
			throw queryError;
		}
	}
}