force-app/main/default/objects/Garbage_Collection_Job__mdt/Garbage_Collection_Job__mdt.object-meta.xml
<CustomObject>
    <description>Each record will create a batch class to delete records of the specified SObjectType</description>
    <label>Garbage Collection Job</label>
    <pluralLabel>Garbage Collection Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>The number of records to be deleted per Database.Batchable execute() call</description>
    <label>Batch Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Garbage_Collection_Jobs</relationshipLabel>
    <relationshipName>Garbage_Collection_Jobs</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/SOQL_Filter__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Filter__c</fullName>
    <description>Sets the WHERE clause for the Garbage Collector batch&apos;s QueryLocator
For more complex filtering, consider referencing an GarbageCollector instance in the &quot;Apex Class Name&quot; field instaed.</description>
    <inlineHelpText>Format: &quot;SELECT Id FROM SObject WHERE ({Your input here})&quot;
ex. &quot;IsClosed = true AND CreatedDate &gt; LAST_N_DAYS:365&quot;</inlineHelpText>
    <label>SOQL Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GarbageCollection/GarbageScheduler_Test.cls
@IsTest
private class GarbageScheduler_Test {
	@IsTest
	static void shouldLaunchActiveJobs() {
		GarbageScheduler instance = new GarbageScheduler();
		instance.activeJobs = getTestJobs(3);
		Test.startTest();
		instance.execute(null);
		Test.stopTest();

		System.assertEquals(instance.activeJobs?.size(), instance.processedJobs?.size(), 'Wrong # of processed jobs');
		System.assertEquals(0, instance.skippedJobs?.size(), 'Wrong # of skipped jobs');
	}

	@IsTest
	static void shouldNotExceedLimit() {
		GarbageScheduler instance = new GarbageScheduler();
		instance.activeJobs = getTestJobs(3);
		instance.flexQueueSize = GarbageScheduler.FLEX_QUEUE_LIMIT;

		Test.startTest();
		instance.execute(null);
		Test.stopTest();

		System.assertEquals(0, instance.processedJobs?.size(), 'Wrong # of processed jobs');
		System.assertEquals(instance.activeJobs?.size(), instance.skippedJobs?.size(), 'Wrong # of skipped jobs');
	}

	@IsTest
	static void shouldExecuteScheduledJob() {
		final String CRON_EXP = '0 0 * * * ?'; // Once hourly
		Id jobId = System.schedule('Test Job', CRON_EXP, new GarbageScheduler());
		System.assertNotEquals(null, jobId, 'Job was not scheduled');
	}

	private static List<Garbage_Collection_Job__mdt> getTestJobs(Integer numJobs) {
		List<Garbage_Collection_Job__mdt> testJobs = new List<Garbage_Collection_Job__mdt>();
		for (Integer i = 0; i < numJobs; i++) {
			testJobs.add(
				new Garbage_Collection_Job__mdt(
					Batch_Size__c = 200,
					SObjectType__c = 'Account',
					SOQL_Filter__c = 'CreatedDate = null'
				)
			);
		}
		return testJobs;
	}
}