force-app/main/default/objects/Garbage_Collection_Job__mdt/Garbage_Collection_Job__mdt.object-meta.xml
<CustomObject>
    <description>Each record will create a batch class to delete records of the specified SObjectType</description>
    <label>Garbage Collection Job</label>
    <pluralLabel>Garbage Collection Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The name of an apex class which can be used to dynamically retrieve a Database.QueryLocator, or a List&lt;SObject&gt;
This allows for more complex SOQL queries that couldn&apos;t otherwise be done in the MDT itself
This class must have a public zero-arg constructor, and implement the IGarbageCollector interface</description>
    <inlineHelpText>This class must have a public zero-arg constructor, and implement the IGarbageCollector interface</inlineHelpText>
    <label>Apex Class Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>The number of records to be deleted per Database.Batchable execute() call</description>
    <label>Batch Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>A unique priority value for all Garbage Collection Jobs.</description>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Garbage_Collection_Jobs</relationshipLabel>
    <relationshipName>Garbage_Collection_Jobs</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/SOQL_Filter__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Filter__c</fullName>
    <description>Sets the WHERE clause for the Garbage Collector batch&apos;s QueryLocator
For more complex filtering, consider referencing an GarbageCollector instance in the &quot;Apex Class Name&quot; field instaed.</description>
    <inlineHelpText>Format: &quot;SELECT Id FROM SObject WHERE ({Your input here})&quot;
ex. &quot;IsClosed = true AND CreatedDate &gt; LAST_N_DAYS:365&quot;</inlineHelpText>
    <label>SOQL Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GarbageScheduler.cls
public without sharing class GarbageScheduler implements System.Schedulable {    
    @TestVisible static final Integer FLEX_QUEUE_LIMIT = 100; 
    
    @TestVisible List<Garbage_Collection_Job__mdt> activeJobs = this.getActiveJobs();
    @TestVisible List<Garbage_Collection_Job__mdt> processedJobs = new List<Garbage_Collection_Job__mdt>();
    @TestVisible List<Garbage_Collection_Job__mdt> skippedJobs = new List<Garbage_Collection_Job__mdt>();
    @TestVisible Integer flexQueueSize = this.getFlexQueueSize(); 
    
    public void execute(System.SchedulableContext context) {
        for (Garbage_Collection_Job__mdt jobMdt : this.activeJobs) {
            if (FLEX_QUEUE_LIMIT > flexQueueSize) {
                GarbageCollector batchJob = GarbageCollector.getInstance(jobMdt).runBatch();
                this.logNewBatch(jobMdt, batchJob.jobId);
                processedJobs.add(jobMdt);
                flexQueueSize++; 
            } else {
                this.skippedJobs.add(jobMdt); 
            }
        }
        this.logSkippedJobs();
        Logger.publish(); 
    }

    private void logNewBatch(Garbage_Collection_Job__mdt jobMdt, Id batchId) {
        final String message = 
            jobMdt.SObjectType__c + ' GarbageCollector job created\n' + 
            'Job Name: ' + jobMdt.DeveloperName + '/n' + 
            'Job Id: ' + batchId;
        Logger.log(LoggingLevel.INFO, message);
    }

    private void logSkippedJobs() {
        if (this.skippedJobs?.isEmpty() == false) {
            final String message = 
                'Could not execute ' + this.skippedJobs?.size() + ' GarbageCollection jobs, ' + 
                'because number of jobs in the Apex Flex Queue (' + FLEX_QUEUE_LIMIT + ').\n' + 
                'Please retry these jobs manually, or wait until the next scheduled run.\n' + 
                'Skipped Jobs: ' + JSON.serializePretty(this.skippedJobs); 
            Logger.log(LoggingLevel.ERROR, message); 
        }
    }

    private List<Garbage_Collection_Job__mdt> getActiveJobs() {
        Soql query = Databaselayer.Soql
            .newQuery(Garbage_Collection_Job__mdt.SObjectType)
            .selectFields(new List<SObjectField>{
                Garbage_Collection_Job__mdt.Apex_Class_Name__c,
                Garbage_Collection_Job__mdt.Batch_Size__c,
                Garbage_Collection_Job__mdt.DeveloperName,
                Garbage_Collection_Job__mdt.SOQL_Filter__c
            }).whereFilters(new Filter(
                Garbage_Collection_Job__mdt.Active__c,
                Filter.EQUALS,
                true
            )).orderBy(new SoqlSort(
                Garbage_Collection_Job__mdt.Priority__c,
                SoqlSort.Order.ASCENDING
            ));
        return (List<Garbage_Collection_Job__mdt>) query.run();
    }

    private Integer getFlexQueueSize() {
        Soql query = Databaselayer.Soql
            .newQuery(AsyncApexJob.SObjectType)
            .whereFilters(new Filter(
                AsyncApexJob.Status,
                Filter.IN_COLLECTION,
                new List<String>{'Holding', 'Pending', 'Processing'}
            ));
        return query.run()?.size(); 
    }
}