force-app/main/default/objects/Garbage_Collection_Job__mdt/Garbage_Collection_Job__mdt.object-meta.xml
<CustomObject>
    <description>Each record will create a batch class to delete records of the specified SObjectType</description>
    <label>Garbage Collection Job</label>
    <pluralLabel>Garbage Collection Jobs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/Apex_Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class_Name__c</fullName>
    <description>The name of an apex class which can be used to dynamically retrieve a Database.QueryLocator, or a List&lt;SObject&gt;
This allows for more complex SOQL queries that couldn&apos;t otherwise be done in the MDT itself
This class must have a public zero-arg constructor, and implement the IGarbageCollector interface</description>
    <inlineHelpText>This class must have a public zero-arg constructor, and implement the IGarbageCollector interface</inlineHelpText>
    <label>Apex Class Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <description>The number of records to be deleted per Database.Batchable execute() call</description>
    <label>Batch Size</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Garbage_Collection_Jobs</relationshipLabel>
    <relationshipName>Garbage_Collection_Jobs</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Garbage_Collection_Job__mdt/fields/SOQL_Filter__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Filter__c</fullName>
    <description>Sets the WHERE clause for the Garbage Collector batch&apos;s QueryLocator
For more complex filtering, consider referencing an GarbageCollector instance in the &quot;Apex Class Name&quot; field instaed.</description>
    <inlineHelpText>Format: &quot;SELECT Id FROM SObject WHERE ({Your input here})&quot;
ex. &quot;IsClosed = true AND CreatedDate &gt; LAST_N_DAYS:365&quot;</inlineHelpText>
    <label>SOQL Filter</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Represents a call to the logging framework. 
For each trigger instance, a &quot;Log Transaction&quot; record will be created. 
For each event instance, a &quot;Log&quot; record will be created.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log_Event__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Indicates the severity of the log message. Values are derived from Apex&apos;s standard LoggingLevel enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm</description>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The contents of the log message.</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/Log_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Log Setting</label>
</CustomObject>

force-app/main/default/objects/Log_Setting__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When unchecked, no logs will be published regardless of the Level</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log_Setting__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <defaultValue>&quot;NONE&quot;</defaultValue>
    <description>Possible values correspond with the standard LoggingLevel Enum:
https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_enum_System_LoggingLevel.htm
Unfortunately, picklists are not available for Custom Settings</description>
    <inlineHelpText>Possible values:
NONE: No logging.
ERROR: Error and exception logging.
WARN: Warning logging.
INFO: Informational logging.
DEBUG: User-specified debug logging.
FINE: High level of logging.
FINER: Higher level of logging than FINE.
FINEST: Highest level of logging.</inlineHelpText>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GarbageCollection/GarbageCollector_Test.cls
@IsTest
private class GarbageCollector_Test {
	static Garbage_Collection_Job__mdt testSoqlJob = new Garbage_Collection_Job__mdt(
		Active__c = true,
		Batch_Size__c = 200,
		SObjectType__c = 'Account',
		SOQL_Filter__c = 'CreatedDate = TODAY'
	);

	static Garbage_Collection_Job__mdt testApexJob = new Garbage_Collection_Job__mdt(
		Active__c = true,
		Apex_Class_Name__c = 'GarbageCollector_Test.TestExtension',
		Batch_Size__c = 200,
		SObjectType__c = 'Account'
	); 

	@IsTest
	static void shouldGenerateScopeUsingSoql() {
		Garbage_Collection_Job__mdt jobMdt = testSoqlJob;

		Test.startTest();
		GarbageCollector batchJob = GarbageCollector.createFromMetadata(jobMdt);
		Test.stopTest();

		System.assertEquals(true, (batchJob instanceof GarbageCollectorSoql), 'Wrong extending type');
		GarbageCollectorSoql scopedJob = (GarbageCollectorSoql) batchJob;
		System.assertEquals(
			true,
			scopedJob.start(null)?.getQuery().contains(jobMdt.SOQL_Filter__c),
			'SOQL Filter was not applied'
		);
		System.assertEquals(100, Database.query(scopedJob.start(null)?.getQuery())?.size(), 'Wrong # of query results');
	}

	@IsTest
	static void shouldGenerateScopeUsingApex() {
		Garbage_Collection_Job__mdt jobMdt = testApexJob;

		Test.startTest();
		GarbageCollector batchJob = GarbageCollector.createFromMetadata(jobMdt);
		Test.stopTest();

		System.assertEquals(true, (batchJob instanceof GarbageCollector_Test.TestExtension), 'Wrong extending type');
		GarbageCollector_Test.TestExtension scopedJob = (GarbageCollector_Test.TestExtension) batchJob;
		System.assertEquals(200, scopedJob.start(null)?.size(), 'Wrong # of records returned');
	}

	@IsTest
	static void shouldDeleteScopedRecords() {
		Garbage_Collection_Job__mdt jobMdt = testSoqlJob;

		Test.startTest();
		GarbageCollector batchJob = GarbageCollector.createFromMetadata(jobMdt).runBatch();
		Test.stopTest();

		System.assertNotEquals(null, batchJob?.jobId, 'A job was not created');
		System.assertEquals(0, queryRecords(Account.SObjectType)?.size(), 'Accounts were not deleted');
		System.assertEquals(100, queryRecords(Lead.SObjectType)?.size(), 'Leads were deleted');
	}

	@IsTest
	static void shouldNotRunIfNoCriteriaDefined() {
		Garbage_Collection_Job__mdt jobMdt = testApexJob;
		jobMdt.Apex_Class_Name__c = null; // No Apex or SOQL defined!

		Test.startTest();
		Exception error;
		try {
			GarbageCollector.createFromMetadata(jobMdt);
		} catch (GarbageCollector.MetadataException caughtError) {
			error = caughtError;
		}
		Test.stopTest();

		System.assertNotEquals(null, error, 'An error was not caught');
	}

	@IsTest
	static void shouldNotRunIfInvalidTypeDefined() {
		Garbage_Collection_Job__mdt jobMdt = testApexJob;
		jobMdt.Apex_Class_Name__c = 'FakeClass';

		Test.startTest();
		Exception error;
		try {
			GarbageCollector.createFromMetadata(jobMdt);
		} catch (GarbageCollector.MetadataException caughtError) {
			error = caughtError;
		}
		Test.stopTest();

		System.assertNotEquals(null, error, 'An error was not caught');
	}

	@IsTest
	static void shouldNotRunIfInvalidQuery() {
		Garbage_Collection_Job__mdt jobMdt = testSoqlJob;
		jobMdt.SOQL_Filter__c = 'THIS SHOULD NOT RUN'; // Leads to an invalid query
		GarbageCollector instance = GarbageCollector.createFromMetadata(jobMdt);

		Exception error;
		try {
			// Note: Placed Test.start/stopTest() inside the try block
			// to catch exceptions thrown DURING the batch execution context
			Test.startTest();
			instance.runBatch();
			Test.stopTest();
		} catch (System.QueryException caughtError) {
			error = caughtError;
		}

		System.assertNotEquals(null, error, 'An error was not caught');
	}

	@IsTest
	static void shouldLogIndividualFailures() {
		// If an error is registered for an individual record, log it
		// Deleting a contact which is tied to a case will generate an error
		Logger.settings = new Log_Setting__c(Enabled__c = true, Level__c = 'FINEST');
		Contact contact = new Contact(LastName = 'Test');
		Databaselayer.Dml.doInsert(contact);
		Databaselayer.Dml.doInsert(new Case(ContactId = contact.Id));
		GarbageCollector instance = new TestExtension();
		Database.BatchableContext mockContext = null;
		List<SObject> scope = new List<SObject>{ contact };

		Test.startTest();
		instance.execute(mockContext, scope);
		Test.stopTest();

		List<Log_Event__e> logEvents = (List<Log_Event__e>) Dml.Published.getAll();
		System.assertEquals(scope?.size(), logEvents?.size(), 'Wrong # of log events: ' + Databaselayer.Dml);
	}

	@IsTest
	static void shouldLogBatchFailure() {
		// If a fatal error is thrown during the execute() method, log it
		Logger.settings = new Log_Setting__c(Enabled__c = true, Level__c = 'FINEST');
		GarbageCollector instance = new TestExtension();
		Database.BatchableContext mockContext = null;
		List<SObject> scope = null;

		Test.startTest();
		Exception error;
		try {
			instance.execute(mockContext, scope);
		} catch (Exception caughtError) {
			error = caughtError;
		}
		Test.stopTest();

		List<Log_Event__e> logEvents = (List<Log_Event__e>) Dml.Published.getAll();
		System.assertEquals(1, logEvents?.size(), 'Wrong # of log events');
		System.assert(logEvents[0].Message__c?.startsWith('Unexpected error'), 'Wrong event logged');
	}

	@TestSetup
	static void setup() {
		List<SObject> records = new List<SObject>();
		for (Integer i = 0; i < 100; i++) {
			records.add(new Account(Name = 'Test Account #' + (i + 1)));
			records.add(new Lead(Company = 'Test Company #' + (i + 1), FirstName = 'John', LastName = 'Doe'));
		}
		records.sort();
		Databaselayer.Dml.doInsert(records);
	}

	static List<SObject> queryRecords(SObjectType objectType) {
		return Databaselayer.Soql.newQuery(objectType).run();
	}

	public class TestExtension extends GarbageCollector {
		// Will delete both Leads & Accounts
		public List<SObject> start(Database.BatchableContext context) {
			List<SObject> records = new List<SObject>();
			records.addAll(queryRecords(Account.SObjectType));
			records.addAll(queryRecords(Lead.SObjectType));
			return records;
		}
	}
}